### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#10]
**Navigation Links**
The navigation bar is located in the top right hand corner of every webpage. It will include the following five navigation buttons and each navigation button should be linked to separate webpages within the website.

`Stories` - pemm.princeton.edu/stories (https://github.com/PrincetonPEMM/pemm-issues/issues/8)
`Paintings`- pemm.princeton.edu/paintings (https://github.com/PrincetonPEMM/pemm-issues/issues/15)
`Manuscripts`- pemm.princeton.edu/manuscripts (https://github.com/PrincetonPEMM/pemm-issues/issues/27)
`Research Tools`- pemm.princeton.edu/research (https://github.com/PrincetonPEMM/pemm-issues/issues/29)
`About` - pemm.princeton.edu/about (refer to https://github.com/PrincetonPEMM/pemm-issues/issues/23)

**Navigation Dropdowns**
Dropdowns appear when user's cursor hovers over each navigation button. Below are the dropdowns for each navigation and their related links: 

`Stories` - no dropdown, clicking on the navigation button takes you to #8 

`Paintings` - three dropdowns, clicking on the navigation button takes you to #15 
1. All Paintings (#15)
2. Paintings by Story (#19)
3. Paintings by Manuscript  (#44)

`Manuscripts` - no dropdown, clicking on the navigation button takes you to #27 

`Research Tools` - nine dropdowns below, clicking on the navigation button takes you to #29 
1. Incipit Tool - will go to /research/incipit-tool
2. Arabic Manuscripts - will go to /research/arabic-manuscripts
3. Arabic Stories - will go to /research/arabic-stories 
4. Maps - will go to /research/maps
5. Interchangeable Spellings of Ethiopic Terms 
6. Research Posts -  will go to /research/research-posts
7. Macomber Handlist - will go to /research/macomber 
8. List of Repositories - will go to /research/repositories (#71)
9. Bibliography - will go to /research/bibliography

`About` - three dropdowns below, clicking on the navigation button takes you to #23 
1. People - will go to /about/people
2. Mission - will go to /about/mission
3. Connect - will go to /about/connect

Please refer to design image below for reference: 

<img width="754" alt="Screen Shot 2022-09-06 at 11 50 19 PM" src="https://user-images.githubusercontent.com/104459635/188735632-abdbd54d-d320-4101-9be6-39f0d7ab2f66.png">

**Comment by elambrinaki** [comment]
The top panel has the following buttons:
`Stories` (#8) 
`Paintings`: a dropdown list with `All Paintings` (#1), `Paintings by Story` (#6), `Paintings by Manuscript` (#44)
`Manuscripts` (#12)
`Research Tools` (#29)
`About` (#23)

**Comment by blainealem** [comment]
Navigation bar, footer, hamburger for mobile view

**Comment by blainealem** [comment]
<img width="754" alt="Screen Shot 2022-09-06 at 11 50 19 PM" src="https://user-images.githubusercontent.com/104459635/188735573-9b5d6d4e-1e34-4a3d-97db-20956a5de979.png">

**Comment by blainealem** [comment]
2/17/2023: 

1) Research Tools needs to be added to the navigation bar

2) Dropdowns need to be included (see above). Research tools should mimic whats in the footer and About should mimic whats in the text (not the reference image).

3) Navigation bar to be shifted right to match design

**Comment by blainealem** [comment]
moved to Phase 2
