### ISSUE TITLE
Story Detail Page

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#11]
This ticket describes the general outline of the 'Story Detail Page'. The page will initially have eight main components, mostly all detailed in other tickets:

- [x] **Title Header [a]**

Located in the top left section the page, this will display the title in header font (refer to photo below).

- [ ] **Autogenerated Text [b]**

In the right column of the page, first paragraph, will be the autogenerated text section providing select details about the story. Note this section does not have a header. Complete guide to this section is documented in separate ticket, #31  

- [ ] **Summary [c]**

Directly under the autogenerated text will be a story "Summary" paragraph. Complete guide to this section is documented in separate ticket, #66. Note that the placement of the Summary paragraph is different for stories with and without paintings, refer to the design photos below.

- [x] **Translation [d]**

Directly under the summary will be an "English Translation"  paragraph. Complete guide to this section is documented in separate ticket #30. Note that the placement of the Summary paragraph is different for stories with and without paintings, refer to the design photos below.

- [ ] **Story Hyperlinks [e]**

After the translation, include hyperlinks to easily access related stories in a Cycle. Many story translations depend on the translations of the stories before and after it and people need to get to them quickly. Complete guide to this section is documented in separate ticket #49 

- [x] **Citation**

Refer to ticket #30 

- [ ] **Other Translations & Editions**

Refer to ticket #30 

- [ ] **Manuscript Information Box[f]**

Underneath the translation is a section of hyperlinked manuscripts names and folios linking all the manuscripts in which the story appears. Complete guide to this section is documented in separate ticket #47  

- [ ] **Painting [g]**

In the top left corner of the page, underneath the title, include a painting for an ID. Complete guide to this section is documented in separate ticket #32. 

- [x] **Information Box[h]**

Underneath the painting in the bottom left corner, this section will include additional details of the story (story type, subjects, keywords, etc).  Complete guide to this section is documented in separate ticket #52 

**[a]** In the PEMM Master file, Canonical Story sheet, Use "Macomber Title" column (column B)
**[b]** Refer to ticket #31 
**[c]** Refer to ticket #66
**[d]** Refer to ticket #30 
**[e]** Refer to ticket #49 
**[f]** Refer to ticket #47  
**[g]** Refer to ticket #32
**[h]** Refer to ticket #52 

Story Detail Page w Painting design
<img width="340" alt="detailPage" src="https://user-images.githubusercontent.com/17439057/164782421-d843bbce-4b2d-409f-91a6-237dda8efbc4.png">

Story Detail Page w/o Painting design 
![image](https://user-images.githubusercontent.com/104459635/177396956-50ee87e1-984a-472f-8e10-782d46aa8f44.png)

**Comment by elambrinaki** [comment]
Page design: 
<img width="340" alt="Story Detail_March 29" src="https://user-images.githubusercontent.com/34317046/160679157-edaf17fd-e33b-45da-a353-b4233fff36d6.png">
