### ISSUE TITLE
7Span: Research Tools: Arabic Manuscripts

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#116]

**Comment by WendyLBelcher** [comment]
Fields for Directus and page:
ResearchTools_ArabicManuscripts_title
ResearchTools_ArabicManuscripts_intro
ResearchTools_ArabicManuscripts_text
ResearchTools_ArabicManuscripts_note (for internal use only, not for display)

**Comment by blainealem** [comment]
Coptic Museum of Cairo, Arabic Manuscript Collection, Manuscript No. 11-8Abbreviation: CM-Ar-Cairo (CM) 11-8Status: Cataloging CompleteStories: 54Link: https://archive.org/details/CMB11-8/page/n1/mode/2upDate: 6 June/5 July, 1687, Date from ms (colophon)Total folios: 226   Total Scans: 243Columns per page: 1   Line range per column: 18–19    Lines per column: 19Folio start of the TM part: 57aTM story paintings: Yes   Scans of Manuscript in Color: NoRepository: Coptic Museum of Cairo  Location: Cairo, Egypt   Lat, Long: 30.00576, 31.2304Catalogers: Jeremy Brown with Ekaterina Pukhovaia
--
St Catherine's Monastery of the Sinai Egypt, SMDL Project No. SCM, Manuscript No. 235Abbreviation: SCM-Ar-Sinai (SMDL) 235Status: Cataloging CompleteStories: 3Link: https://sinaimanuscripts.library.ucla.edu/catalog/ark:%2F21198%2Fz19s38qgDate: 16th century, Date from catalogTotal folios: 208   Total Scans: 434Columns per page: 1   Line range per column: 13–15    Lines per column: 14Folio start of the TM part: 92rTM story paintings: No   Scans of Manuscript in Color: YesRepository: St. Catherine's Monastery of the Sinai  Location: Sinai, Egypt   Lat, Long: 28.55556, 33.97611Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Séminaire Sainte-Anne de Jérusalem, HMML Project ID SSAJ, Manuscript No. 60Abbreviation: SSAJ-Ar-Jerusalem (HMML) 60Status: Cataloging CompleteStories: 4Link: https://w3id.org/vhmml/readingRoom/view/511374Date: 19th, Date from catalogTotal folios: 200   Total Scans: 207Columns per page: 1   Line range per column: 24–26    Lines per column: 25Folio start of the TM part: 61vTM story paintings: No   Scans of Manuscript in Color: YesRepository: Séminaire Sainte-Anne de Jérusalem  Location: Jerusalem, Israel   Lat, Long: 31.78106, 35.23644Catalogers: Jeremy R. Brown
Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 69Abbreviation: V-Ar-Paris (BNF) 69Status: Cataloging CompleteStories: 15Link: https://gallica.bnf.fr/ark:/12148/btv1b11000397wDate: 1334, Date from catalogTotal folios: 243   Total Scans: 249Columns per page: 1   Line range per column: 10–13    Lines per column: 10Folio start of the TM part: 98vTM story paintings: No   Scans of Manuscript in Color: NoRepository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 155Abbreviation: V-Ar-Paris (BNF) 155Status: Cataloging CompleteStories: 44Link: https://gallica.bnf.fr/ark:/12148/btv1b110047379Date: 1486, Date from catalogTotal folios: 138   Total Scans: 145Columns per page: 1   Line range per column: 21–22    Lines per column: 21Folio start of the TM part: 1rTM story paintings: No   Scans of Manuscript in Color: NoRepository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 177Abbreviation: V-Ar-Paris (BNF) 177Status: Cataloging CompleteStories: 12Link: https://gallica.bnf.fr/ark:/12148/btv1b11004087qDate: 1289, Date from catalogTotal folios: 189   Total Scans: 190Columns per page: 1   Line range per column: 17–18    Lines per column: 17Folio start of the TM part: 115vTM story paintings: No   Scans of Manuscript in Color: NoRepository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 263Abbreviation: V-Ar-Paris (BNF) 263Status: Cataloging CompleteStories: 2Link: https://gallica.bnf.fr/ark:/12148/btv1b11004024wDate: Before 1531, Date from catalogTotal folios: 206   Total Scans: 213Columns per page: 1   Line range per column: 11–23    Lines per column: 14Folio start of the TM part: 101rTM story paintings: No   Scans of Manuscript in Color: NoRepository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 265Abbreviation: V-Ar-Paris (BNF) 265Status: Cataloging CompleteStories: 1Link: https://gallica.bnf.fr/ark:/12148/btv1b11004621tDate: 1600s, Date from catalogTotal folios: 174   Total Scans: 186Columns per page: 1   Line range per column: 11–14    Lines per column: 14Folio start of the TM part: 77rTM story paintings: No   Scans of Manuscript in Color: NoRepository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 4771Abbreviation: V-Ar-Paris (BNF) 4771Status: Cataloging CompleteStories: 74Link: https://gallica.bnf.fr/ark:/12148/btv1b10030629qDate: 1800s, according to Baraz, Date from catalogTotal folios: 295   Total Scans: 298Columns per page: 1   Line range per column: 16    Lines per column: 16Folio start of the TM part: 1vTM story paintings: No   Scans of Manuscript in Color: NoRepository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. Syr. 232Abbreviation: V-Ar-Paris (BNF) Syr. 232Status: Cataloging CompleteStories: 65Link: https://gallica.bnf.fr/ark:/12148/btv1b10088687m/f546.itemDate: 1600s, Date from catalogTotal folios: 592   Total Scans: 617Columns per page: 2   Line range per column: 23–29    Lines per column: 26Folio start of the TM part: 523rTM story paintings: No   Scans of Manuscript in Color: NoRepository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Biblioteca Apostolica Vaticana, [Arabic Manuscript Collection], Manuscript No. 170Abbreviation: V-Ar-Vatican (BAV) 170Status: Cataloging CompleteStories: 77Link: digi.vatlib.it/view/MSS_Vat.ar.170Date: 1719, Date from ms (colophon)Total folios: 333   Total Scans: 341Columns per page: 1   Line range per column: 15    Lines per column: 15Folio start of the TM part: 6vTM story paintings: No   Scans of Manuscript in Color: NoRepository: Biblioteca Apostolica Vaticana  Location: Rome, Italy   Lat, Long: 41.90477, 12.45495Catalogers: Jeremy Brown with Ekaterina Pukhovaia
Biblioteca Apostolica Vaticana, [Arabic Manuscript Collection], Manuscript No. 821Abbreviation: B-Ar-Vatican (BAV) 821Status: Cataloging Incomplete: not digitizedStories: 0Link: Date: 1700s, Date from catalogTotal folios:    Total Scans: Columns per page:    Line range per column:     Lines per column: Folio start of the TM part: TM story paintings: Unknown   Scans of Manuscript in Color: NoRepository: Biblioteca Apostolica Vaticana  Location: Rome, Italy   Lat, Long: 41.90477, 12.45495Catalogers:
British Library, Great Britain India Office Arabic Manuscripts, Manuscript No. 27AAbbreviation: L-Ar-India (BL) 27AStatus: Cataloging Incomplete: not digitizedStories: 0Link: Date: , Total folios:    Total Scans: Columns per page:    Line range per column:     Lines per column: Folio start of the TM part: TM story paintings: Unknown   Scans of Manuscript in Color: NoRepository: British Library  Location: London, England   Lat, Long: 51.53005, -0.12766258Catalogers:
Coptic Museum of Cairo, Arabic Manuscript Collection, Manuscript No. 05-12Abbreviation: CM-Ar-Cairo (CM) 05-12Status: Cataloging CompleteStories: 77Link: https://archive.org/details/cmb-5-12/mode/2upDate: -11685, Date from ms (colophon)Total folios: 238   Total Scans: 240Columns per page: 1   Line range per column: 18    Lines per column: 18Folio start of the TM part: 239TM story paintings: No   Scans of Manuscript in Color: NoRepository: Coptic Museum of Cairo  Location: Cairo, Egypt   Lat, Long: 30.00576, 31.2304Catalogers: Jeremy Brown with Ekaterina Pukhovaia

**Comment by WendyLBelcher** [comment]
### "Coptic Museum of Cairo, Arabic Manuscript Collection, Manuscript No. 11-8
Abbreviation: CM-Ar-Cairo (CM) 11-8
Status: Cataloging Complete
Stories: 54
Link: https://archive.org/details/CMB11-8/page/n1/mode/2up
Date: 6 June/5 July, 1687, Date from ms (colophon)
Total folios: 226   Total Scans: 243
Columns per page: 1   Line range per column: 18–19    Lines per column: 19
Folio start of the TM part: 57a
TM story paintings: Yes   
Scans of Manuscript in Color: No
Repository: Coptic Museum of Cairo  Location: Cairo, Egypt   Lat, Long: 30.00576, 31.2304
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"

### "St Catherine's Monastery of the Sinai Egypt, SMDL Project No. SCM, Manuscript No. 235
Abbreviation: SCM-Ar-Sinai (SMDL) 235
Status: Cataloging Complete
Stories: 3
Link: https://sinaimanuscripts.library.ucla.edu/catalog/ark:%2F21198%2Fz19s38qg
Date: 16th century, Date from catalog
Total folios: 208   Total Scans: 434
Columns per page: 1   Line range per column: 13–15    Lines per column: 14
Folio start of the TM part: 92r
TM story paintings: No   
Scans of Manuscript in Color: Yes
Repository: St. Catherine's Monastery of the Sinai  Location: Sinai, Egypt   Lat, Long: 28.55556, 33.97611
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Séminaire Sainte-Anne de Jérusalem, HMML Project ID SSAJ, Manuscript No. 60
Abbreviation: SSAJ-Ar-Jerusalem (HMML) 60
Status: Cataloging Complete
Stories: 4
Link: https://w3id.org/vhmml/readingRoom/view/511374
Date: 19th, Date from catalog
Total folios: 200   Total Scans: 207
Columns per page: 1   Line range per column: 24–26    Lines per column: 25
Folio start of the TM part: 61v
TM story paintings: No   
Scans of Manuscript in Color: Yes
Repository: Séminaire Sainte-Anne de Jérusalem  Location: Jerusalem, Israel   Lat, Long: 31.78106, 35.23644
Catalogers: Jeremy R. Brown"
"Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 69
Abbreviation: V-Ar-Paris (BNF) 69
Status: Cataloging Complete
Stories: 15
Link: https://gallica.bnf.fr/ark:/12148/btv1b11000397w
Date: 1334, Date from catalog
Total folios: 243   Total Scans: 249
Columns per page: 1   Line range per column: 10–13    Lines per column: 10
Folio start of the TM part: 98v
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 155
Abbreviation: V-Ar-Paris (BNF) 155
Status: Cataloging Complete
Stories: 44
Link: https://gallica.bnf.fr/ark:/12148/btv1b110047379
Date: 1486, Date from catalog
Total folios: 138   Total Scans: 145
Columns per page: 1   Line range per column: 21–22    Lines per column: 21
Folio start of the TM part: 1r
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 177
Abbreviation: V-Ar-Paris (BNF) 177
Status: Cataloging Complete
Stories: 12
Link: https://gallica.bnf.fr/ark:/12148/btv1b11004087q
Date: 1289, Date from catalog
Total folios: 189   Total Scans: 190
Columns per page: 1   Line range per column: 17–18    Lines per column: 17
Folio start of the TM part: 115v
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 263
Abbreviation: V-Ar-Paris (BNF) 263
Status: Cataloging Complete
Stories: 2
Link: https://gallica.bnf.fr/ark:/12148/btv1b11004024w
Date: Before 1531, Date from catalog
Total folios: 206   Total Scans: 213
Columns per page: 1   Line range per column: 11–23    Lines per column: 14
Folio start of the TM part: 101r
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 265
Abbreviation: V-Ar-Paris (BNF) 265
Status: Cataloging Complete
Stories: 1
Link: https://gallica.bnf.fr/ark:/12148/btv1b11004621t
Date: 1600s, Date from catalog
Total folios: 174   Total Scans: 186
Columns per page: 1   Line range per column: 11–14    Lines per column: 14
Folio start of the TM part: 77r
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. 4771
Abbreviation: V-Ar-Paris (BNF) 4771
Status: Cataloging Complete
Stories: 74
Link: https://gallica.bnf.fr/ark:/12148/btv1b10030629q
Date: 1800s, according to Baraz, Date from catalog
Total folios: 295   Total Scans: 298
Columns per page: 1   Line range per column: 16    Lines per column: 16
Folio start of the TM part: 1v
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Bibliothèque nationale de France, [Arabic Manuscript Collection], Manuscript No. Syr. 232
Abbreviation: V-Ar-Paris (BNF) Syr. 232
Status: Cataloging Complete
Stories: 65
Link: https://gallica.bnf.fr/ark:/12148/btv1b10088687m/f546.item
Date: 1600s, Date from catalog
Total folios: 592   Total Scans: 617
Columns per page: 2   Line range per column: 23–29    Lines per column: 26
Folio start of the TM part: 523r
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Bibliothèque nationale de France  Location: Paris, France   Lat, Long: 48.83285, 2.37867
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Biblioteca Apostolica Vaticana, [Arabic Manuscript Collection], Manuscript No. 170
Abbreviation: V-Ar-Vatican (BAV) 170
Status: Cataloging Complete
Stories: 77
Link: digi.vatlib.it/view/MSS_Vat.ar.170
Date: 1719, Date from ms (colophon)
Total folios: 333   Total Scans: 341
Columns per page: 1   Line range per column: 15    Lines per column: 15
Folio start of the TM part: 6v
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Biblioteca Apostolica Vaticana  Location: Rome, Italy   Lat, Long: 41.90477, 12.45495
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
"Biblioteca Apostolica Vaticana, [Arabic Manuscript Collection], Manuscript No. 821
Abbreviation: B-Ar-Vatican (BAV) 821
Status: Cataloging Incomplete: not digitized
Stories: 0
Link: 
Date: 1700s, Date from catalog
Total folios:    Total Scans: 
Columns per page:    Line range per column:     Lines per column: 
Folio start of the TM part: 
TM story paintings: Unknown   
Scans of Manuscript in Color: No
Repository: Biblioteca Apostolica Vaticana  Location: Rome, Italy   Lat, Long: 41.90477, 12.45495
Catalogers: "
"British Library, Great Britain India Office Arabic Manuscripts, Manuscript No. 27A
Abbreviation: L-Ar-India (BL) 27A
Status: Cataloging Incomplete: not digitized
Stories: 0
Link: 
Date: , 
Total folios:    Total Scans: 
Columns per page:    Line range per column:     Lines per column: 
Folio start of the TM part: 
TM story paintings: Unknown   
Scans of Manuscript in Color: No
Repository: British Library  Location: London, England   Lat, Long: 51.53005, -0.12766258
Catalogers: "
"Coptic Museum of Cairo, Arabic Manuscript Collection, Manuscript No. 05-12
Abbreviation: CM-Ar-Cairo (CM) 05-12
Status: Cataloging Complete
Stories: 77
Link: https://archive.org/details/cmb-5-12/mode/2up
Date: -11685, Date from ms (colophon)
Total folios: 238   Total Scans: 240
Columns per page: 1   Line range per column: 18    Lines per column: 18
Folio start of the TM part: 239
TM story paintings: No   
Scans of Manuscript in Color: No
Repository: Coptic Museum of Cairo  Location: Cairo, Egypt   Lat, Long: 30.00576, 31.2304
Catalogers: Jeremy Brown with Ekaterina Pukhovaia"
