### ISSUE TITLE
7Span: Research Tools: Interchangeable spellings of Ethiopic Terms

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#118]

**Comment by WendyLBelcher** [comment]
Directus and page:
ResearchTools_Spellings_title
ResearchTools_Spellings_intro
ResearchTools_Spellings_text
ResearchTools_Spellings_note (for internal use only, not for display on the page

**Comment by WendyLBelcher** [comment]
[Title field content:]
Interchangeable spellings of Ethiopic Terms
[Intro field content:]
The peoples of the northern and central Eritrean and Ethiopian highlands have their own unique script, a syllabary with charactrs representing a consonant and vowel. Called fidäl, they created it in the 200s CE and use it for their Afro-Asiatic language of Gǝˁǝz and other local languages.  Gǝˁǝz has around forty basic consonant characters and seven vowels, which, in combination with their preceding consonants, are represented through a basic fidäl symbol and six modifications of it. This means that the that complete fidäl set it comprises more than three hundred symbols or glyphs. The vowels of fidäl are:[this will have five or six paragraphs]
[Text field content:]
