### ISSUE TITLE
7Span: Research Tools: Research Posts

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#119]

**Comment by WendyLBelcher** [comment]
Fields for Directus and page:
ResearchTools_ResearchPosts_title
ResearchTools_ResearchPosts_intro
ResearchTools_ResearchPosts_id
ResearchTools_ResearchPosts_text
ResearchTools_ResearchPosts_note (for internal use only, not for display on the page

This page will have more than one research post. Scholar A will write a few paragraphs on the paintings; Scholar B will write a few paragraphs on Story ID 13; Scholar C will write a few paragraphs about the data on how many stories were translated from Arabic into Ge'ez, etc. 

Now that I think about it, I realize that ResearchPosts also needs detail pages. But, I will confirm with Blaine.

**Comment by WendyLBelcher** [comment]
Rationale for Wendy only:
Scholar A will write a few paragraphs on the paintings; Scholar B will write a few paragraphs on Story ID 13; Scholar C will write a few paragraphs about the data on how many stories were translated from Arabic into Ge'ez, etc.
