### ISSUE TITLE
Manuscript Index Page

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#12]

**Comment by elambrinaki** [comment]
Page design (with facets and without):

![Manuscript Index_facets shown](https://user-images.githubusercontent.com/34317046/160673999-36cade6b-0076-4d04-9c09-e746c4726e74.png)

![Manuscript Index_facets hidden](https://user-images.githubusercontent.com/34317046/160674013-0e0ba815-c7b6-4880-9294-b9a994b9c7a4.png)
