### ISSUE TITLE
7Span: Research Tools: Bibliography

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#121]
Fields for Directus and page:
ResearchTools_Bibliography_title
ResearchTools_Bibliography_intro
ResearchTools_Bibliography_text
ResearchTools_Bibliography_note (for internal use only, not for display on the page)

**Comment by WendyLBelcher** [comment]
Text to copy and paste into ResearchTools_Bibliography_text:
Anonymous. 192B2. "The Conception and Birth of Our Lady Mary (Book of James)." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 122-142. London: Oxford University Press, H. Milford.

Anonymous. 192C2. "The Covenant of Christ with the Blessed Virgin Mary Commonly Called the Covenant of Mercy." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 54-60. London: Oxford University Press, H. Milford.

Anonymous. 192F2. "The History of the Flight of the Virgin Mary to Mount Lebanon." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 202-235. London: Oxford University Press, H. Milford.

Anonymous. 192G2. "The Annunciation of Gabriel to Mary." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 102-121. London: Oxford University Press, H. Milford.

Anonymous. 192H2. "The History of Hanna." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 1-53. London: Oxford University Press, H. Milford.

Anonymous. 192J2. "The History of the Death of the Virgin Mary as told by St John." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 152-167. London: Oxford University Press, H. Milford.

Anonymous. 192O2. "The Oration on the Nativity by Demetrius of Antioch." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, xxxiii-xxxi. London: Oxford University Press, H. Milford.

Anonymous. 192S2. "Salutations to the Members of the Body of the Virgin Mary." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 236-244. London: Oxford University Press, H. Milford.

Anonymous. 192Th2. "The History of the Virgin Mary by Theophilus Patriarch of Alexandria." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 61-80. London: Oxford University Press, H. Milford.

Anonymous. 192Ti2. "The History of the Virgin Mary by Timothy Patriarch of Alexandria." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 81-101. London: Oxford University Press, H. Milford.

Anonymous. 192V2. "The Vision of the Virgin Mary which She Told to John the Son of Zebedee." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 245-278. London: Oxford University Press, H. Milford.

Anonymous. 192W2. "The History of the Departure of the Virgin Mary from This World." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 168-201. London: Oxford University Press, H. Milford.

Anonymous. 192We2. "Weddase Maryam (The Book of the Praise of Mary)." In Legends of Our Lady Mary the Perpetual Virgin and Her Mother Hanna, edited by E. A. Wallis Budge, 279-296. London: Oxford University Press, H. Milford.

Anonymous. 193M3. "Introduction to the Miracles of the Virgin Mary." In One Hundred and Ten Miracles of Our Lady Mary, edited by E. A. Wallis Budge, xlvi-liv. London: Oxford University Press, H. Milford.

Anonymous. 1600s. Art Institute of Chicago: Täˀammərä Maryam In Art Institute of Chicago.

Anonymous. 1800s. Princeton Ethiopic Manuscript No. 43: Tä’ammərä Maryam. In Princeton University Library Ethiopic Manuscripts. Princeton.

Anonymous. 1924. "[Summary of the] Apocalypse of the Virgin (Ethiopic)." In The Apocryphal New Testament: being the apocryphal gospels, acts, epistles, and apocalypses, with other narratives and fragments, edited by Montague Rhodes James, 563-4. Oxford, UK: Clarendon Press.

Anonymous, ed. 1958. Mäṣḥafä Qəddase bä-Gəˁəz ənna bä-Amarəñña [The Book of Liturgy in Gəˁəz and Amharic]. Addis Ababa, Ethiopia: Täsfa Gäbrä Śəllase Printing Press.

Anonymous. 1991 [1954]. The Liturgy of the Ethiopian Church. Translated by Murqus Dāwūd. Edited by Marsie Hazen. Kingston, Jamaica: Ethiopian Orthodox Church. Original edition, 1954.

Anonymous. 2005. "Protevangelium of James." In New Testament Apocrypha: Volume 1: Gospels and Related Writings, edited by William Schneemelcher and R. McL. Wilson, 426-439. Louisville, London: J. Clarke & Company; Westminster John Knox Press.

Apter, Emily. 2014. Against world literature: On the politics of untranslatability: Verso Books.

Arenberg, Meg. 2016. "Converting Achebe’s Africa for the New Tanzanian: Things Fall Apart in Swahili Translation." Eastern African Literary and Cultural Studies 2 (3-4):124-135.

Arens, William. 1979. The Man-Eating Myth: Anthropology and Anthropophagy: Oxford University Press, USA.

Arras, Victor. 1973. De transitu Mariae: Apocrypha Aethiopice I, Corpus scriptorum christianorum orientalium 342-343, Scriptores Aethiopici 66-67, 1–84 (text) = 1–54 (tr.). Leuven, Belgium: Secrétariat du CSCO.

Arras, Victor. 1974. De transitu Mariae: Apocrypha Aethiopice II, Corpus scriptorum christianorum orientalium 351-352, Scriptores Aethiopici 68-69, 1–33 (text) = 1–25 (tr.), 56–61 (text) = 43–46 (tr.). Leuven, Belgium: Secrétariat du CSCO.

Atiya, Aziz Suryal, ed. 1991. The Coptic Encyclopedia: Volume 3. 8 vols. Vol. 3. New York: Macmillan.

Auerbach, Erich. 2013 [1953]. Mimesis: The Representation of Reality in Western Literature: The Representation of Reality in Western Literature. Princeton: Princeton University Press.

Augustine of Hippo. 2005. Letters 211-270. Translated by Roland J. Teske and Boniface Ramsey. Edited by Boniface Ramsey and John E. Rotelle. Vol. Part 2, Volume 4, The Works of Saint Augustine: A Translation for the 21st Century: Augustinian Heritage Institute. New York: New City Press.

Aymro Wondmagegnehu, and Joachim Motovu. 1970. The Ethiopian Orthodox Church. Addis Ababa, Ethiopia.
Balicka-Witakowska, Ewa. 1998. "The Crucified Thieves in Ethiopian Art. Literary and Iconographical Sources." Oriens Christianus 82:204–56.
