### ISSUE TITLE
Paintings Index Page: Implement Filter or faceted search

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#15]

**Comment by WendyLBelcher** [comment]
I want to do a faceted search of paintings, so that I can find paintings, say, made in the 1300s or in manuscripts at the British Library. As discussed with Anisa, we are proposing a dropdown faceted search at the top of the page. I forget what page she had given us as an example. 

The five facets that I want to search are:
**Date of Painting.** Researchers want to be able to restrict the paintings they are viewing to a particular period/century. We have several fields in the database that provide this information, in the Manuscripts sheet, and we should discuss how to use them.
**Painting in Color?** Researchers want to be able to restrict the paintings they are viewing to only color images, that is, excluding all black and white images, which are digitized microfilm. We do not have this field yet, so we need to create it in the Manuscript sheet. Ask Jeremy to do this.
**Story Type.** Researchers want to be able to restrict the paintings they are viewing to those about Mary's life (e.g., Madonna and child, the Annunciation). We have a field for this in the Canonical Story sheet.
**Archive of Painting.** Researchers want to be able to restrict the paintings they are viewing to those at a particular archive, such as only those at Princeton or the British Library. We do have this field, in the Collections sheet.
**Objects Depicted.** Researchers want to be able to restrict the paintings they are viewing to those with particular objects (e.g., knives, stools). We are creating this metadata in the paintings sheet, under Episode keywords.
**Agents Depicted.** Researchers want to be able to restrict the paintings they are viewing to those with particular living things (e.g., monks, forests, camels, Archangel Gabriel). We are creating this metadata in the paintings sheet, under Episode keywords.
**Activities Depicted.** Researchers want to be able to restrict the paintings they are viewing to those with particular activities (e.g., eating, sleeping, hunting, praying). We are creating this metadata in the paintings sheet, under Episode keywords.
**Associated Concepts Depicted.** Researchers want to be able to restrict the paintings they are viewing to those with particular conditions or ideas (e.g., disease, disability, heaven, hell). We are creating this metadata in the paintings sheet, under Episode keywords.
**PEMM Story ID.** Researchers want to be able to restrict the paintings they are viewing to those for particular story IDs. The ID is on the paintings page.

[Paintings List Page.docx](https://github.com/WendyLBelcher/pemm-website/files/8234108/Paintings.List.Page.docx)


- One question I have is, will it be tough to do a faceted search across the top of the paintings index page, but a faceted search across the left side of the page for the story index page?

**Comment by henokalem** [comment]
test `hi`

**Comment by henokalem** [comment]
Sample design of faceted search
<img width="364" alt="indexPaintingsFacetedSearch" src="https://user-images.githubusercontent.com/17439057/159065718-9f01e29b-2901-4b43-91db-e2411407f3cb.png">

**Comment by elambrinaki** [comment]
Updated design:
![Paintings Index_facets](https://user-images.githubusercontent.com/34317046/161244467-6ed063a9-752a-48d4-8f75-d7c0b9c81383.png)
