### ISSUE TITLE
Paintings Index page: Implement information about each painting next to it

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#17]

**Comment by WendyLBelcher** [comment]
As a researcher, I want to see some information about the painting. 

Question? I may want to see it immediately, always visible below the painting or I may want to see it on hover. Hover is more complicated to program. Also, I think I want to be able to skim quickly, not have to put my cursor over paintings.
Question? I may want to see the story title but I think I may prefer to see the episode title. It may be a little contextually vague, but it will describe exactly what is happening in the painting.

**Date of paintings.** I want to see the century in which the painting was made. 
**Manuscript name.** I want to see which manuscript the painting comes from
**Folio.** I want to see on which folio of the manuscript the painting appears. 
**Episode title.** I want to see the episode title, which describes what is happening in the painting.

![Paintings List Index page paintings](https://user-images.githubusercontent.com/56000106/157925975-e2747fe0-7086-472f-90e0-0ef67296e84a.png)

**Comment by blainealem** [comment]
moved to Phase 2
