### ISSUE TITLE
Story Index Page: Faceted Search

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#21]
As a researcher, I want to be able to do powerful searches on the story index page. I want to click on boxes in a faceted search to limit my results (by date and so on), and I want to be able to sort my findings (by date and so on). 

**Facets:** (for design, see the picture below)

In the Filtered Search, in the following pairs make the other option unavailable if the alternative is chosen:

- Miracle of Mary stories & Life of Mary stories
- Earliest stories & Recent stories 
- Popular stories & Unique stories

`Filtered Search`
- With paintings [Column L "Total Paintings" in Canonical Story Sheet >0]
- Most illustrated [Column L "Total Paintings" in Canonical Story Sheet >19]
- With English translation [if column AO "English Translation Status" in Canonical Story Sheet  is not empty or "summary only"]
- Ethiopian stories [Column C "Origin" in Canonical Story Sheet contains the word "Ethiopia"]
- Miracle of Mary stories [Column AM "Type of Story" in Canonical Story Sheet has the value "Miracle of Mary"]
- Life of Mary stories [Column AM "Type of Story" in Canonical Story Sheet has the value "Life of Mary"] 
- Earliest stories [Column BT "Early Attestation by Ms Date Range Mean" in Canonical Story Sheet if <=1400]
- Recent stories [Column BT "Early Attestation by Ms Date Range Mean" in Canonical Story Sheet if >1950]
- Popular stories [Column K "Total Records" in Canonical Story Sheet if >200]
- Unique stories [Column K "Total Records" in Canonical Story Sheet =1]

- [ ] `Story's Estimated Date of Origin`
[Column BT "Early Attestation by Ms Date Range Mean" in Canonical Story Sheet]
format: timeline

- [ ] `Story's Place of Origin`
[Column C "Origin" in Canonical Story Sheet ="...Africa..." then Africa; ="...Ethiopia..." then "Ethiopia"; if blank = "Unknown"]
format: chips placed in a line
Africa (452 records)
Egypt (83 records)
Ethiopia (363 records)
Europe (63 records)
France (6 records)
Spain (5 records)
Levant (23 records)
Unknown (427 records)

- [ ] `Type of Story` 
[column AM "Type of Story" in Canonical Story sheet]
format: chips
Miracle of Mary
Life of Mary
Homily

- [ ] `Number of Manuscripts with Story` 
[Column K "Total Records" in Canonical Story Sheet]
format: timeline

- [ ] `Number of Paintings of Story`
[Column L "Total Paintings" in Canonical Story Sheet]
format: timeline

- [ ] `Story Available in Languages` 
[Column six to pull from: BH "Appears in French" BI "Appears in Amharic" BJ "Appears in Latin" BK "Appears in Italian" AL "Appears in Arabic" = if "yes" then "French" etc. If AO "English Translation Status" if not empty or "summary only" then "English"]
format: chips
Gəˁəz (968 records)
Arabic
Amharic (407 records)
English
French (181 records)
Italian (45 records)
Latin (24 records)

- [ ] Instead of `Collection`, create new filters (Historical figure, cycle, etc.)

**Comment by henokalem** [comment]
<img width="143" alt="storyIndexFacetSearch" src="https://user-images.githubusercontent.com/17439057/159067162-6f58dd0d-dd1d-4b56-99fd-dcdf412c0cc6.png">

**Comment by WendyLBelcher** [comment]
The faceted search would be for:
ID. This would be the new` PEMM ID Number.`

**Comment by WendyLBelcher** [comment]
We need a faceted search for the Story Index page, as shown in this pdf. [3PEMM Story Index Web Pages.pdf](https://github.com/WendyLBelcher/pemm-website/files/8309784/3PEMM.Story.Index.Web.Pages.pdf)

**Comment by WendyLBelcher** [comment]
![Story Faceted Search](https://user-images.githubusercontent.com/56000106/159132380-0de91fe9-4ea0-4dff-8bc3-49f1995c9554.png)

**Comment by elambrinaki** [comment]
- [ ] With paintings
Most illustrated
With English translation
Ethiopian stories
Post-life stories
Life of Mary stories
Earliest stories
Recent stories
Popular stories 
Rare stories

- [ ] `Story's Century of Origin` (see the data [here](https://docs.google.com/spreadsheets/d/1oqtqcmqdI59IivjChBuIzRuwVzz1ndC0nhUT4-AEh5A/edit#gid=1641084486))
1300s (8 records)
1400s (217 records)
1500s (241 records)
1600s (66 records)
1700s (56 records)
1800s (137 records)
1900s (238 records)

- [ ] `Story's Place of Origin`

**Comment by elambrinaki** [comment]
- [ ] The faceted search window might be hidden if one clicks on the "Hide" button at the top of the faceted search box. From the hidden view, one might get to the full view by clicking "Show Options".
![Story Index_facets shown](https://user-images.githubusercontent.com/34317046/160643869-f9add629-cefb-4137-abef-83832492f8fa.png)

![Story Index_facets hidden](https://user-images.githubusercontent.com/34317046/160643894-0b7192e0-cfd4-4eae-a580-91ea7663c9f2.png)

**Comment by blainealem** [comment]
@ayo-gb Can you please remove 'France' as an option for 'Language of Story' search

**Comment by blainealem** [comment]
Example of search filters in Princeton Geniza Project:

<img width="219" alt="Screen Shot 2022-09-21 at 3 47 35 PM" src="https://user-images.githubusercontent.com/104459635/191508156-885e3892-8e40-4dc4-a2db-9285c6199c57.png">
