### ISSUE TITLE
PEMM Website Structure

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#24]
This ticket describes the general outline of the PEMM website. The page will have several components, mostly all detailed in other tickets: (as of June 2022):

- [ ] **Home Page:**
This is the first page users see when accessing http://pemm.princeton.edu. Complete guide to this section is documented in separate ticket, #9 

- [ ] **Map**
An illustrated Google Map to display location of manuscripts. Complete guide to this section is documented in separate ticket, #28

**Comment by elambrinaki** [comment]
Current plan regarding the Home/Landing Navigation buttons:
`Stories `leads to the Story Index page (#8) only, from which one can access individual stories' Story Detail pages (#11).
`Paintings` is a dropdown with three options: Paintings Index (#1), Paintings by Story (#19), Paintings by Manuscript (#44).
`Manuscripts` leads to the Manuscript Index page (#12) only, from which one can access individual manuscripts' Manuscript Detail pages (#13).

**Comment by WendyLBelcher** [comment]
[`Paintings` navigation button goes to:]
- Paintings Index/List Page [with typed search, faceted search, and sort function]
- Paintings Detail Page [with all paintings for one story]
- Paintings Individual [with zoom on individual painting]
- Painting Episodes page [no paintings, just a list of story titles with the paintings episodes]

[`Stories `navigation button goes to:]
- Stories Index/List Page [with typed search, faceted search, and sort function]
- Stories Detail Page [with all PEMM information for one story]

[`Manuscripts `navigation button goes to:]
- Manuscript Index/List Page [with typed search???, faceted search, and sort function]
- Manuscript Detail Page [with all PEMM information for one manuscript]

[`Research Tools` navigation button goes to:]
- PEMM Gəˁəz Incipit Tool [dynamic]
- Research Posts [static]
- List of Repositories [dynamic]
- Bibliography [static? Or, linked?]
- Using the Site [static]

[`About `navigation button goes to:]
- About [page with links to the static pages below]
- Our Mission [static page]
- Our Team [static page]
- Our Partners [static page]
- Our History [static page]
- 
- Volunteer [static page]
- 
- Media Coverage [Static page]
- Project Updates [Static page]
- Events & Workshops [Static page]

**Comment by WendyLBelcher** [comment]
[`Paintings` navigation button goes to:]
- Paintings Index/List Page [with typed search, faceted search, and sort function]
- Paintings Detail Page [with all paintings for one story]
- Paintings Individual [with zoom on individual painting]
- Painting Episodes page [no paintings, just a list of story titles with the paintings episodes]

**Comment by WendyLBelcher** [comment]
[`Research Tools` navigation button goes to:]
- PEMM Gəˁəz Incipit Tool [dynamic]
- Research Posts [static]
- List of Repositories [dynamic]
- Bibliography [static? Or, linked?]
- Using the Site [static]

[`About `navigation button goes to:]
- About [page with links to the static pages below]
- Our Mission [static page]
- Our Team [static page]
- Our Partners [static page]
- Our History [static page]
- 
- Volunteer [static page]
- 
- Media Coverage [Static page]
- Project Updates [Static page]
- Events & Workshops [Static page]

**Comment by blainealem** [comment]
[The following navigation buttons across top of the page]

- `Stories`
- `Paintings`
- `Manuscripts`
- `Tools`
- `About`

Web page addresses for these will be /stories, /paintings, /manuscripts, /tools, /about

Home/Landing page will have three images/tiles--titled `Featured Stories`, `Featured Paintings`, `Featured Manuscripts`. When you click on one of them, it takes you down the landing page to three tiles. 

- When you click on `Featured Stories`, it will take you to down the Home page to three tiles, with the words over each of them: Cannibal of Qemer, Healed Daughter, Pregnant Abbess (over the top of selected images). When you click on one of the tiles/images, it will take you to **static** pages with the web addresses /featured/stories/125 (using the Macomber ID No. for the story), and so on.
- When you click on `Featured Manuscripts`, it will take you to three tiles/images, with the words over each of them: EMML 9002, PEM 65, and BOr 520. If you click on them they will take you to the dynamic pages for those manuscripts (so not /featured/manuscripts/EMML9002, but /manuscripts/EMML9002, and so on.
- When you click on `Featured Paintings`, it will take you to three tiles/images, which will be [a, b, c]. Clicking on each will take you to static pages with the web addresses /featured/paintings/125 (using the Macomber ID No. for the associated story), and so on.

**Comment by WendyLBelcher** [comment]
**Web Design.** 

- We are using the following colors: Green 3C6F57, Yellow E5A942, Red DA232A, Off-White E7E3DC, Black 221F21. 
- We are using the following fonts: Header font (for logo mainly), Body font (Source Serif), Title font (Bold Source Serif), Menu font (Source non-Serif), Geez body font (Noto Serif and Noto Serif Bold). 

[Pemm design guidelines colors fonts.pdf](https://github.com/PrincetonPEMM/pemm-issues/files/9302902/Pemm.design.guidelines.colors.fonts.pdf)
