### ISSUE TITLE
Manuscript Index Page: Faceted search on Manuscript Index page

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#27]

**Comment by elambrinaki** [comment]
- [ ] With paintings
With color scans
With online copy
With unique stories
Oldest manuscripts
Newest manuscripts

- [ ] `Date Manuscript Created`
1300s
1400s
1500s
1600s
1700s
1800s
1900s

- [ ] `Manuscript's Number of Stories `(see the data [here](https://docs.google.com/spreadsheets/d/1z5AacPcEblVpxLGHtup7A0_CBfY_V_HJ4giP0FmZlEE/edit#gid=0) )
More than 300 (25 records)
200 to 300 (27 records)
100 to 199 (105 records)
40 to 99 (132 records)
30 to 39 (67 records)
10 to 29 (20 records)
6 to 9 (14 records)

- [ ] `Manuscript's Number of Unique Stories` (see the data [here](https://docs.google.com/spreadsheets/d/1zYSfnAeoOg9fnreZxz6J9-qjXZpJh74mCZnohDuun_4/edit#gid=0))
More than 50 (1 record)
10 to 50 (2 records)
2 to 9 (12 records)
1 (25 records)
None (390 total manuscripts records minus 40 manuscripts with unique stories =  350 records)

- [ ] `Manuscript's Number of Paintings` (see the data [here](https://docs.google.com/spreadsheets/d/1NmWMyQeT0X3vuYmtYzN4id2n1NPZQ6Nj6gZBwkEOiw4/edit#gid=0))
More than 50 (9 records)
25 to 50 (13 records)
1 to 10 (9 records)

- [ ] `Region Manuscript Created In` (see the data [here](https://docs.google.com/spreadsheets/d/1jVe2CEJbbexGtTv1DWD_ZHGXykf3kWsq0k35qX5JXhs/edit#gid=0))
Addis Ababa (40 records)
Eritrea (3 records)
Gojjam (16 records)
Gondar (12 records)
Gondar area (22 records)
Oromia (1 record)
Shoa (54 records)
Tanasee ( records)
Tigray (94 records)
Wallo (33 records)
Jerusalem (3 records)
unknown (111 records)

**Comment by henokalem** [comment]
Additionally add a place of origin faceted search origin. Design is still in progress.
