### ISSUE TITLE
Research Tools "Page" Links

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#29]
As a user, I want to find information that doesn't appear in the main pages for Stories, Paintings, and Manuscripts. As a creator, I want all our carefully collected data to appear somwhere.

**Comment by elambrinaki** [comment]
- [ ] Arabic Manuscripts
- [ ] Arabic Stories
- [ ] Map

**Comment by WendyLBelcher** [comment]
The pages for the Research Tools could be the following:
1. Incipit Tool - will go to /research/incipit-tool 
2. Arabic Manuscripts - will go to /research/arabic-manuscripts
3. Arabic Stories - will go to /research/arabic-stories  
4. Maps - will go to /research/maps
5. Interchangeable Spellings will go to /research/spellings
6. Research Posts -  will go to /research/research-posts
7. Macomber Handlist - will go to /research/macomber 
8. List of Repositories - will go to /research/repositories 
9. Glossary - will go to /research/glossary
10. Bibliography - will go to /research/bibliography
11. Using the Site - will go to /research/using-site
12. Data Archive - will go to /research/archive

Note different wording: **Interchangeable Spellings** not **Interchangeable Spellings of Ethiopic Terms**
