### ISSUE TITLE
Story Detail Page: Translation & Citation

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#30]
As of Feb 25, 2022, the below is correct about how to list the translators. It is not correct about the Other Translations and Editions. For that, go to ticket #76 

******************************************************

This ticket details the Translation paragraph as well as citations. The translation paragraph is located underneath the summary paragraph. Note that the placement of the Translation paragraph is different for stories with and without paintings, refer to the design photos below.

**Translation**
Use header font (smaller than Story Title Header, refer to the "Translation" header in the image below). 

Underneath the header will include a "Translated by" author field [a] and "from" manuscript name and folio [b] "in" translation year [c].

Underneath the "Translated by" begins the actual english translation [d]. Note only translations that only have `canonical_translation_recension` checked (boolean) will appear on the website. Loop through for each story ID to identify if `canonical_translation_recension` is checked (boolean) then pull the followoing fields

Example: Translated by Jeremy Brown, from BOr (BL) 650, ff. 28r-35v, in 2022.

**[a]** In the PEMM Master file, Translation sheet, Use `translation_author`
**[b]** In the PEMM Master file, Translation sheet, Use `translation_source_manuscript_name`and `translation_source_manuscript_folio`. Two data points should be separated by a comma (ex: EMML 3695, 20v-25r)
**[c]** In the PEMM Master file, Translation sheet, Use `Translation_as_of_date`
**[d]** In the PEMM Master file, Translation sheet, Use `translation_text" column`

~Directly under the Translation will be the story cycle hyperlink which lets people easily access stories in the same cycle. This is include in a separate ticket, #49~ postponed as Phase 2 task

**Translation Citation**
After the cycle hyperlink, the translation citation will appear. The citation should include the following attributes which are all located in columns from the PEMM Master file, Canonical Story sheet:

1) `translation_author`
2) `canonical_story_ID`
3) `translation_title`
4) The following text "Täˀammərä Maryam (Miracle of Mary) Stories,_ edited by Wendy Laura Belcher, Jeremy Brown, Mehari Worku, and Dawit Muluneh. Princeton: Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary project."
5) The following url: "http://pemm.princeton.edu/story-detail/000X" (generated URL of story detail page, X = canonical_story_id, column A)
6) Last Modified date xxx (`Translation_as_of_date`)

Please see below for an example: 
Jeremy Brown & Dawit Muluneh. "ID 0001 Bishop of Hildefonsus." Täˀammərä Maryam (Miracle of Mary) Stories, edited by Wendy Laura Belcher, Jeremy Brown, Mehari Worku, and Dawit Muluneh. Princeton: Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary project. http://pemm.princeton.edu/story-detail/0001. Last Modified: 2022

IGNORE THIS SECTION and use #76 
**Other Translations & Editions** 
This should be a separate paragraph with a header titled "Other Translations". This section is included to provide the citations for translations in different languages. Under the "Other translation header will have lines for each language. Ex: 
Amharic: (translation citation here)
French: (translation citation here)

If the story only appears in Ge'ez and no other language, that is if columns AL, BH, BI, BJ, and BK all = no, please omit the "Other Translation" paragraph.

Amharic Citation
All manuscripts written in Amharic are from TGS manuscripts. In order to determine which TGS manuscript/citation is required, we need to perform the following: 
~-In the PEMM Master file, 'Canonical Story Sheet' refer to column BY "TGS?" If column has a value that means it is an TGS manuscripts.~
*Updated*
In the PEMM Master file, 'Story Instance Sheet' refer to column B for story ID and column A for  manuscript 

- [x] If column A = TGS (EOTC) 1968 use the following citation and be sure to include the folio page at the end: 
Täsfa Giyorgis, ed. Täˀammərä Maryam Bä-Gəˁəz Ənna Bä-Amarəñña [the Miracles of Mary in Gəˁəz and Amharic: 111 Miracles]. 2nd ed. Addis Ababa, Ethiopia, 1968, page <insert folio start page here - column CB>

- [x] If column A = TGS (EOTC) 1971 use the following citation and be sure to include the folio page at the end: 
Täsfa Gäbrä Śəllase, ed. Täˀammərä Maryam Bä-Gəˁəz Ənna Bä-Amarəñña [the Miracles of Mary in Gəˁəz and Amharic: Part One: 270 Miracles]. Addis Ababa, Ethiopia: Täsfa Gäbrä Śəllase Printing Press, 1971, page <insert folio start page here - column E>

- [ ] If column A = TGS (EOTC) 1994 use the following citation and be sure to include the folio page at the end: 
 Täsfa Gäbrä Śəllase, ed. Täˀammərä Maryam Bä-Gəˁəz Ənna Bä-Amarəñña [the Miracles of Mary in Gəˁəz and Amharic: Part Two: 402 Miracles]. Addis Ababa, Ethiopia: Täsfa Gäbrä Śəllase Printing Press, 1994, page <insert folio start page here - column E>

- [x] If column A = TGS (EOTC) 1996 use the following citation and be sure to include the folio page at the end: 
 Täsfa Gäbrä Śəllase, ed. Täˀammərä Maryam Bä-Gəˁəz Ənna Bä-Amarəñña [the Miracles of Mary in Gəˁəz and Amharic: Part Two: 402 Miracles]. Addis Ababa, Ethiopia: Täsfa Gäbrä Śəllase Printing Press, 1996, page <insert folio start page here - column E>

- [x] If column A = TGS (EOTC) 2014 use the following citation and be sure to include the folio page at the end:
 Gäbrä Śəllase Bərhan, ed. Täˀammərä Maryam Bä-Gəˁəz Ənna Bä-Amarəñña [the Miracles of Mary in Gəˁəz and Amharic: 366 Miracles]. Aksum, Ethiopia: Gäbrä Śəllase Bərhan Printing Press, 2014, page <insert folio start page here - column E>

French Citation: 
-In the PEMM Master file, `Canonical Story Sheet`  if `Appears in French ` (column BH) is **True** insert the following text: 

French Translation in Colin, Gérard. _Le Livre Éthiopien Des Miracles De Marie (Taamra Mâryâm)._ Paris: Les Editions du Cerf, 2004, item [column AB]

Ge'ez Print Edition: 
-In the PEMM Master file, `Canonical Story Sheet` if column Q (Print Version) has a value, insert the following text: 

Ge'ez Print Edition(s): [data in column Q]

Story Detail Page Design with painting:
https://user-images.githubusercontent.com/17439057/164782421-d843bbce-4b2d-409f-91a6-237dda8efbc4.png

Story Detail Page Design without painting:
![image](https://user-images.githubusercontent.com/104459635/177401103-006e65b2-52cc-468c-9178-fa329cc01755.png)

Please ignore these translation for now and focus only on the French & Amharic: (@WendyLBelcher to update according to new translation sheet)
-From the  `Canonical Story Sheet`  if `Appears in Latin` (column BJ) is **True** then use [more instructions needed here]

-From the  `Canonical Story Sheet`  if `Appears in Arabic` (column AL) is **True** then use the Story Instance sheet to pull the relevant manuscript [more instructions needed here]

-From the  `Canonical Story Sheet`  if `Appears in Italian` (column BK) is **True** then use x and put this in front of it: Italian Translation in Cerulli, Enrico. _Il Libro Etiopico Dei Miracoli Di Maria E Le Sue Fonti Nelle Letterature Del Medio Evo Latino. Universita Di Roma, Studi Orientali Pubblicati a Cura Della Scuola Orientale_. Rome: Giovanni Bardi Editore, 1943. [more instructions needed here]

Print Version (column Q) only has one TGS currently, in the future we can look at all TGSs

**Comment by issacjohannli** [comment]
> **6. Last Modified date x.xx.xxx (when the page last changed)**
> 
> Please see below for an example: Jeremy Brown & Dawit Muluneh. "ID 0001 Bishop of Hildefonsus." Täˀammərä Maryam (Miracle of Mary) Stories, edited by Wendy Laura Belcher, Jeremy Brown, Mehari Worku, and Dawit Muluneh. Princeton: Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary project. http://pemm.princeton.edu/story-detail/0001. **Last Modified: 2.8.2022.**

Hi @blainealem, I hope all is well! 

There's been great progress on the translation & citation of the story detail page.

Where could I obtain the last modified date? Is it the current date on which the page is loaded?

Thank you!

**Comment by blainealem** [comment]
Hi @issacjohannli yes that is correct, it is the current date the user accesses the page.

**Comment by blainealem** [comment]
Hi @issacjohannli we have decided to remove the lat modified date portion entirely. This may be something we focus on in third year but you can ignore it for now. Thank you.

**Comment by issacjohannli** [comment]
@WendyLBelcher @blainealem 

 The list below shows the changes in the information widget and the translation/citation of the story detail page:

- Renamed `Total Instances in GMP` as `Total Manuscripts in which Story Appears`
- Does the `Earliest Attested Instance of the Story` use both Story Instance Sheet `Manuscript Date Range Start` (column AM) and `Manuscript Date Range End` (column AN)? If so, it is 1700-1799 ***
- Added an ellipses  `...`  between the incipit and the manuscript source
- Recension ID of Story 13 is `null`, so it is currently not displayed
- The **order** and the **name** of the ID Numbers are rearranged and amended respectively
- Punctuation of the citation box is edited (added a colon) - `ID 13: The composition of ...`
- Italicized the citations of French and Italian translations
- Bolded the categories of Other Translations & Editions - `Amharic:`, `Italian:`, `French:`, `Ge'ez Print Edition(s):`etc.

<img width="1372" alt="information-widget-and-translation-and-citation-updated" src="https://user-images.githubusercontent.com/67703799/177875036-2141a223-e791-4685-848c-d8ac60c429a5.png">

**Comment by blainealem** [comment]
Hi @issacjohannli per review of the 'Other Translations & Editions' section, we have a few comments below: 

1) For Amharic translation, we need to change the current formula. As of right now, there is only one TGS folio that appears in column BY on the 'Canonical Story' sheet. However each stories can appear in multiple TGS manuscripts (either TGS 1968, 1971, 1996, and 2014) and we need to include if the story appears in multiple manuscripts. Is it possible to loop through the 'Story Instance' sheet in the PEMM master file by canonical story ID (column B) and generate all the TGS manuscripts (can refer to column A or column BC) the story appears, while also including the folio start page (column E on the story instance sheet) for each TGS manuscript. Let me know if this makes sense. Happy to go through this with you live. 

2) Please remove the Italian edition information. Currently the data is incorrect and more instructions are needs on how to cite the edition.

**Comment by blainealem** [comment]
- [ ] Please update to include the text "in" and data from field <translation as of date> from translation sheet right after the translated by and manuscript/foilio. See reference image below. 
[01 Story Detail page revised WLBe.pdf](https://github.com/PrincetonPEMM/pemm-issues/files/10794588/01.Story.Detail.page.revised.WLBe.pdf)

**Comment by blainealem** [comment]
Hi @issacjohannli we have a few comments on the citation section below: 

- [ ] translation_author - correct, no issues

- [ ] canonical_story_ID - correct, no issues

- [ ] translation_title - the title is cut off, please include the complete title

- [ ] The following text "Täˀammərä Maryam (Miracle of Mary) Stories,_ edited by Wendy Laura Belcher, Jeremy Brown, Mehari Worku, and Dawit Muluneh. Princeton: Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary project." - correct, no issues

- [ ] The following url: "http://pemm.princeton.edu/story-detail/000X" (generated URL of story detail page, X = canonical_story_id, column A) - the url needs to be updated to say "stories" instead of "story-detail"

- [ ] Last Modified date xxx (Translation_as_of_date) - This should be pulled from the translation sheet. currently the website shows todays date

- [ ] **NEW** - We like that you included the current date. However, the wording that appears before that should be "Date Accessed". So, it would look like Date Accessed: 3.21.2023
