### ISSUE TITLE
Story Detail Page: Implement the auto generated text area

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#31]
As a user, I want to have basic information about the story.

**Comment by elambrinaki** [comment]
- [ ] The top box with descriptive statistics

The information is in prose with autogenerated fields (whether the story is old/new, what century it was composed, in what percent of manuscripts it appears, etc.)

The columns needed for this: Canonical Story page, columns "PEMM ID", "Macomber Title", "Earliest Attestation", "Origin", "Total Records", "Total Paintings", "Appears in Arabic", "Appears in French", "Appears in Amharic", "Appears in Latin", "Appears in Italian"

- [ ] The box on the left below the images
`Story Type`: (use column "Non-Life Miracle" on the Canonical Story sheet: if "No", spell "Life of Mary Miracle", if "Yes", spell "Post-Life Miracle")
`Subjects`: (Canonical Story Subject)
`Collection`:
`Keywords`: use "PEMM Keywords and Translations" file, sheet "[Story Keywords]([url](https://docs.google.com/spreadsheets/d/1PEAJ1fnxh4VQWU1XsOmeY6ZHUHQNDSmNQzwvNfN-Z0M/edit#gid=259395083))", column ???)
`Incipit`: (Canonical Incipit)
`Number of incipits in PEMM Incipit Tool`: (Total Incipits in the ITool)
`Published translation`:  (if "English Translation Status" column has "Published translation", use "English Translation Source" column, see #30. Otherwise, spell "None".)
`Manuscript source for English translation`: (use columns English Translation Manuscript Name and English Translation Manuscript Folio)
`Translation Author`: (if there is a published translation cited above, skip this field. If there is no translation (English Translation Status column is empty), skip this field. Otherwise, use )
`ID numbers:` (Hamburg ID, CSM Number, Poncelet Number, Clavis ID, Macomber ID)
`Earliest manuscripts in which story appears`: (Names of Mss with Earliest Attestation)

<img width="340" alt="4PEMM Story Detail page" src="https://user-images.githubusercontent.com/34317046/160262579-8dda7614-2240-45f3-8cfc-5ded990c578f.png">

**Comment by blainealem** [comment]
Tested some of the new features on this link, and noticed the following that needs to be updated: 

1) All stories show as "very recent" instead of very old etc. 
2) Looking forward to seeing [b], [c], [d] - Henok needs to update API for "Total Records" column - link to ticket for API
3) Updated the ticket above to remove the summary section and link to summary ticket 
4) If data is missing for any field, remove the sentence

**Comment by blainealem** [comment]
Hi @ayo-gb and @henokalem, per review of the auto-generated text section we've noted the following that needs to be updated: 

1) For [b], we noted that the sentence reads, "The earliest GMP (Gəˁəz manuscripts in the PEMM database) in which this story appears is from the -100s." Can you double check why the date appears as a negative 100s?

2) For [j], we noted that the website only includes that language English. Reminder that all stories should include Ge'ez and this story in particular (311) should also include French (column BG) and Amharic (column BH)
