### ISSUE TITLE
Story Index page: Title View & Detail View

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#38]
- [ ] **Title View**

The title view button (located in the top right hand corner of the story index page) allows a user to see a plain list of story titles to scroll through. This plain list generated either through the full list or the results of a faceted search, displays ins the titles of the story and not any of the supporting details. 

This is how the titles only page looks like. To get back to full details, one would click "Detail View" button 
![Story Index_title view](https://user-images.githubusercontent.com/34317046/160650379-cfcc3863-de4b-4cc2-bc34-c99cad6aec70.png)

- [ ] **Detail View**

The detail view button (same as the title view) allows a user to see a complete list of story titles and supporting details (origin, paintings, etc. )

![transition detail view to title view](https://user-images.githubusercontent.com/34317046/160650904-45179bce-0fe2-4c75-be5e-a352c01a085c.png)

**Comment by blainealem** [comment]
Hi @henokalem per inspection of the ethiopicmary.com website, we noted that the story index page needs the following updates: 

1) There is a lot of space between the story title and the supporting details underneath. Is it possible to pull the detail view line closer to the title line and also have less space between titles
