### ISSUE TITLE
Manuscript Index Page: Linking manuscripts names from Manuscript Index page to Manuscript Detail page

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#39]
As a user, I want to be able to access detailed information about a manuscript from the Manuscript Index page, i.e. move to the Manuscript Detail page.

**Comment by elambrinaki** [comment]
In the list of manuscripts, each manuscript name is hyperlinked to the Manuscript Detail page (See https://github.com/WendyLBelcher/pemm-website/issues/13.)

**Comment by blainealem** [comment]
moved to phase 2
