### ISSUE TITLE
Manuscript Detail Page: Implement autogenerated text widget

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#41]

**Comment by elambrinaki** [comment]
The top box with descriptive statistics (autogenerated data):

Manuscript Name

British Library "Orient" Collection, Manuscript No. 520
This Gəˁəz language manuscript was created in the 1600s, likely in the royal scriptorium in Gondar. 
It has 32 Marian miracle stories and no unique stories. 
It has 59 paintings of Marian miracle stories. It has a total of 267 folios, with 2 columns per page, approximately 13 lines per column, and 8 characters per line. The Marian miracle stories begin on folio 137r of the manuscript. 
To view the entire manuscript online, which was digitized in color, see the digital copy. 
The stories in this manuscript were cataloged by Jeremy Brown. 
Beta maṣāḥǝft ID: BLorient520
Catalog ID: Wright, William. Catalogue of the Ethiopic Manuscripts in the British Museum Acquired since the Year 1847. London: British Museum, 1877. No. 47

![Manuscript Detail_ms description](https://user-images.githubusercontent.com/34317046/160683848-def0ed2a-00c7-4a6e-8a70-ad2ea47fc52a.png)

**Comment by elambrinaki** [comment]
- [ ] @WendyLBelcher we need to come up with rules for naming the manuscripts (British Library "Orient" Collection, Manuscript No. 520 is currently BOr (BL) 520 in the database)

**Comment by WendyLBelcher** [comment]
@ayo-gb maybe it makes sense to have you work on this auto-generated part, and have @issacjohannli  work on the table of cataloging?

**Comment by WendyLBelcher** [comment]
Data for Wendy (not needed for programmers) 
TOTAL STORIES | 976 |  
% OF STORIES W MORE THAN 300 RECORDS | 1.02% |  
% OF STORIES W MORE THAN 200 RECORDS | 4.10% |  
% OF STORIES W MORE THAN 100 RECORDS | 12.60% |  
% OF STORIES W MORE THAN 50 RECORDS | 24.90% |  
% OF STORIES W MORE THAN 25 RECORDS | 36.17% |  
% OF STORIES W MODE RECORD | 22.85% | Percent of stories that have 1 record
MEDIAN RECORD | 7 | 50% of stories have 7 records or less
MAX RECORDS | 404 | Highest # of records in one story
MIN RECORDS | 1 | Lowest # of records in one story

MODE RECORD | 1 | # of records that repeat most frequently
COUNTMODE | 223 | 223 stories have 1 record
