### ISSUE TITLE
Manuscript Detail Page: Implement cataloged miracle records in the manuscript

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#42]

**Comment by elambrinaki** [comment]
- [ ] The table with cataloged data. Columns:
PEMM Story ID
PEMM Story Title
Folio Range (if both Folio Start and Folio End data is present, use the format "5r-6v", otherwise give the Folio Start only ("5r")). Note: some records have Scan Start and Scan End instead of Folio Start and Folio End—use those and spell "scan".
Order in Marian Stories in Manuscript
Confidence Score
Incipit (remove the column if there is no data)
Story Paintings (give the number of paintings and folios—use columns "Number of Paintings" and "Painting Note" in the Story Instance sheet)

**Comment by elambrinaki** [comment]
- [ ] on hover explanations of table headers

**Comment by WendyLBelcher** [comment]
@issacjohannli maybe it makes sense to have you work on this, and have @ayo-gb work on the auto-generated part at the top?

**Comment by WendyLBelcher** [comment]
First, can you remove the ID Certainty data. I realize that is really an internal category, we don't need the public to see it. Second, can you make the incipit field last? Switch it with paintings? Third, if possible, can you keep the title and incipit columns wide, but narrow the other columns? We need as much space as possible for the title and incipit and the other columns will only ever have four to five characters in them. Again, happy to do a Github ticket with this. (ed

**Comment by WendyLBelcher** [comment]
- [ ] make the incipit field last. Switch it with paintings

**Comment by WendyLBelcher** [comment]
Notes in Slack on Miracle Records in Manuscript on April 14, 2023
Question 1. Incipits. Many manuscripts will have no incipits typed for any story. That is, out of 3 to 400 stories, not one will have an incipit typed. Could we say, if the incipit field is empty for all stories in one manuscript, then we hide the incipit field? And, it would be cool if we could make the title column wider and thus give more space for long titles, but I realize that is tough. 

Question 3. Hyperlinks. Hyperlinking to the story detail page is so awesome. I think either the ID or the title should be hyperlinked, not both. I'm a little worried that if the whole title is hyperlinked, it is going to be blue and underlined or something and thus tough to read? If there is a way to make it easy to read, then my preference would be to have a link on the title. 

Question 4. Incipit length. Most readers won't care about the incipit. So, I think that a hide expand feature is great. I'm wondering about the title and incipit length possibly matching. That is, is there a way where, if the story title is short, you see little of the incipit but if the title is long you see more of the incipit? Like, their lengths match? I doubt it, but I thought I would ask. 
New Question 5. Header wording. Evgeniia noted in github that we might want to have a "on hover" explanations of table headers. I'm not sure they are needed, what do you think?

New Question 6. ID Certainty. I had noted in Github to "remove the ID Certainty data. I realize that is really an internal category, we don't need the public to see it." But, most manuscripts will have no story with a certainty id other than high. Probably 75 to 90%. Could we say, if the ID Certainty field is always high for all stories in one manuscript, then we hide the  ID Certainty field? 
New Question 7. Paintings. Most manuscripts will have no paintings for any story. Probably 75%. Could we say, if the painting field is empty for all stories in one manuscript, then we hide the painting field? 
New Question 8. Recension field. Evgeniia and I forgot to include one field. :disappointed: We need the recension_id field. The field header would be Story Recension by MS 
New Question 9. Stanza field. Evgeniia and I forgot to include another field. :disappointed: We need the stanza field. The field header would be Story Includes Hymn Lyrics.  Most manuscripts will have no stanza for any story. Probably 90%. Could we say, if the stanza field is empty for all stories in one manuscript, then we hide the stanza field? (edited) 



New Question 10. Popularity. I think it would be great to mark if a story is unique to that manuscript. Like, it only appears once in all our manuscripts and that once is in this manuscript. But, the easiest way to do that is to just put a Total Records column, right? The field header would be Total Story Records  Well, that's not great. Story Popularity? Total MSS Story Appears In. Maybe that last one is best. (edited) 



**

- [ ] New Question 11. Column order and fields included.

** Maybe it is Story ID (always present), Story Title  (always present), ID Certainty (column omitted if no story in manuscript has a low or medium ID Certainty), Paintings of Story in This MS (column omitted if no story in manuscript has paintings), Total MSS Story Appears In  (always present),  Location in MS  (always present), Number in MS (always present)  Story Recension by MS (always present), Story Includes Hymn Lyrics.  (column omitted if no story in manuscript has stanza), Incipit (the first unique line of the story in this manuscript) (column omitted if no story in manuscript has incipits). If it is easier to program always present first, that's okay with me, we can move paintings to later. (edited)

**Comment by WendyLBelcher** [comment]
- [ ] New Question 7. Paintings. 

Most manuscripts will have no paintings for any story. Probably 75%. Could we say, if the painting field is empty for all stories in one manuscript, then we hide the painting field? 

- [ ] New Question 8. Recension field. 

Evgeniia and I forgot to include one field. :disappointed: We need the recension_id field. The field header would be Story Recension by MS 

- [ ] New Question 9. Stanza field. 

Evgeniia and I forgot to include another field. :disappointed: We need the stanza field. The field header would be Story Includes Hymn Lyrics.  Most manuscripts will have no stanza for any story. Probably 90%. Could we say, if the stanza field is empty for all stories in one manuscript, then we hide the stanza field? 

- [ ] New Question 10. Popularity.

 I think it would be great to mark if a story is unique to that manuscript. Like, it only appears once in all our manuscripts and that once is in this manuscript. But, the easiest way to do that is to just put a Total Records column, right? The field header would be Total Story Records  Well, that's not great. Story Popularity? Total MSS Story Appears In. Maybe that last one is best. 

- [ ] New Question 11. Column order and fields included.
Maybe it is Story ID (always present), Story Title  (always present), ID Certainty (column omitted if no story in manuscript has a low or medium ID Certainty), Paintings of Story in This MS (column omitted if no story in manuscript has paintings), Total MSS Story Appears In  (always present),  Location in MS  (always present), Number in MS (always present)  Story Recension by MS (always present), Story Includes Hymn Lyrics.  (column omitted if no story in manuscript has stanza), Incipit (the first unique line of the story in this manuscript) (column omitted if no story in manuscript has incipits). If it is easier to program always present first, that's okay with me, we can move paintings to later. (edited)

And, it would be cool if we could make the title column wider and thus give more space for long titles, 
- [ ] New Question 5. Header wording. Evgeniia noted in github that we might want to have a "on hover" explanations of table headers. I'm not sure they are needed, what do you think?

**Comment by WendyLBelcher** [comment]
- [ ] New Question 11. Column order and fields included.
Maybe it is Story ID (always present), Story Title  (always present), ID Certainty (column omitted if no story in manuscript has a low or medium ID Certainty), Paintings of Story in This MS (column omitted if no story in manuscript has paintings), Total MSS Story Appears In  (always present),  Location in MS  (always present), Number in MS (always present)  Story Recension by MS (always present), Story Includes Hymn Lyrics.  (column omitted if no story in manuscript has stanza), Incipit (the first unique line of the story in this manuscript) (column omitted if no story in manuscript has incipits). If it is easier to program always present first, that's okay with me, we can move paintings to later. (edited)

**Comment by WendyLBelcher** [comment]
For future

- [ ] **Header wording**. Evgeniia noted in github that we might want to have a "on hover" explanations of table headers. I'm not sure they are needed, what do you think?
- [ ] **Story Title.** And, it would be cool if we could make the title column wider and thus give more space for long titles. NO, it is fine.

**Comment by issacjohannli** [comment]
> * Where to put ` recension_id` (rare) add that wording after a comma
>   _Example:_ 201, Recension EMML (HMML) 3275 [Note: Ask Jeremy about changing these into one and two?]

@WendyLBelcher @elambrinaki @blainealem - Has this been decided upon?

**Comment by issacjohannli** [comment]
> * **Header wording**. Evgeniia noted in github that we might want to have a "on hover" explanations of table headers. I'm not sure they are needed, what do you think?

@WendyLBelcher @elambrinaki @blainealem - Would you like to explain the header wordings with a tooltip on hover? (Please see example concept below)

<img width="220" alt="Screenshot 2023-05-08 at 5 29 51 PM" src="https://user-images.githubusercontent.com/67703799/236878618-a8cb0a46-819a-465a-ae13-cde8a177e9dc.png">

**Comment by blainealem** [comment]
> > * **Header wording**. Evgeniia noted in github that we might want to have a "on hover" explanations of table headers. I'm not sure they are needed, what do you think?
> 
> <img alt="Screenshot 2023-05-08 at 5 53 48 PM" width="1268" src="https://user-images.githubusercontent.com/67703799/236884553-56f29f4f-0d69-4c0a-9061-b527a1f1d3a8.png">
> 
> @WendyLBelcher @elambrinaki @blainealem - Would you like to explain the header wordings with a tooltip on hover? (Please see example concept below)
> 
> <img alt="Screenshot 2023-05-08 at 5 29 51 PM" width="220" src="https://user-images.githubusercontent.com/67703799/236878618-a8cb0a46-819a-465a-ae13-cde8a177e9dc.png">
