### ISSUE TITLE
Paintings by Manuscript Page (all paintings in a particular manuscript)

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#44]
As a user, I want to see all the Täˀammərä Maryam paintings in a manuscript.

**Comment by elambrinaki** [comment]
- [ ] To see all the paintings from a manuscript, one would click on the hyperlink in the manuscript description telling the number of paintings. 
![Manuscript Detail_ms description](https://user-images.githubusercontent.com/34317046/160698122-f91ddb9c-2f87-4da2-b08b-7bb533d9d08e.png)

- [ ] To see illustrations for a particular story in the given manuscript, one would click on the painting data for a miracle record in the cataloged table.

![Manuscript Detail_cataloged data](https://user-images.githubusercontent.com/34317046/160698139-866563d1-e30f-4bc1-8b8e-7c78a079c549.png)

**Comment by blainealem** [comment]
moved to phase 2
