### ISSUE TITLE
7Span: Home Page: Featured Stories

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#45]
7Span:
Featured Stories is the first of the three tiles that will appear on the home page. Featured Stories has the following elements: 

**Title**
'Featured Stories' header will appear in title font (refer to design below) over the home page top left image. When user hovers over the title, the following prose will appear in smaller text: 

_"Stories about the Virgin Mary in Ethiopia, Eritrea, and Egypt are vivid, profound, and intriguing. The PEMM website includes 1,000+ of these African folktales, composed from 1200 CE to the present."_

**Story Reveal**
When you click on 'Featured Stories' tile, you move down the page to three tiles (refer to design below). Each tile will have an illustration of a story [a] with the story title [b] located on top of the illustration. 
1) A Daughter's Education (Macomber ID 111)
2) Thirsty Dog (ID 236)
3) Ethiopian King (Macomber ID 319)

Above the tiles will be a paragraph titled "Featured Stories" that will have the following text: 

_"Read a story about a girl's education and healing (from Egypt), one about kindness to animals (from Ethiopia), and one about a king's speaking icon (from Ethiopia)."_

**Story Link**
Each tile should be a link to the story's detail page:
1) A Daughter's Education -  /stories/111 
2) Thirsty Dog -  /stories/236 
3) Ethiopian King - /stories/319

[a] - Story illustrations
[b] - Story titles can be found in PEMM master file, 'Canonical Story' tab, column 'Macomber Title' (column B)

**Reference design  for Title**
<img width="675" alt="Screen Shot 2022-07-12 at 3 59 30 PM" src="https://user-images.githubusercontent.com/104459635/178611127-7c3b1ac4-887f-453f-9145-ddafb6821033.png">

**Reference design  for Story Reveal**
<img width="806" alt="Screen Shot 2022-07-12 at 6 47 42 PM" src="https://user-images.githubusercontent.com/104459635/178611254-be2863c8-b680-4d10-b5bc-e28845c6c52e.png">

**Comment by elambrinaki** [comment]
The idea of the featured story page is three stories on one page
The paintings will not necessarily be associated directly with that story, but be borrowed. So, if 68 dogs, use a holy family painting.

Story feature page would have no left menu. Just the story and a clickable link.
We won't put Amharic here because it will be localized later, so it will have dedicated Amharic translation pages

**Comment by blainealem** [comment]
Alternative suggestions previously noted for featured stories: 
Mary Giving Water to a Dog in a Shoe
The Bishop Makes a Book for Mary

**Comment by WendyLBelcher** [comment]
Update: Anisa is coming up with a stylized design for the three Featured Stories. The first is a stylized water/Nile concept (for the Healed Daughter story, Macomber ID 111), and then maybe a stylized image of shoes with water in them, and/or Mary’s hand, and/or the dog’s face ( for the Thirsty Dog story, ID 236), and then a crown or something (for the Ethiopian King story, Macomber ID 319). We talked about this a couple of times and this was communicated through Slack but Slack only keeps that for a few months, so I’m not sure if you can find that there. But, I think my summary here is enough.

**Comment by blainealem** [comment]
moved to Phase 2
