### ISSUE TITLE
7Span: Home Page: Featured Paintings

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#46]
Featured Paintings is the last of the three tiles that will appear on the home page. Featured Paintings has the following elements:

**Title**
'Featured Paintings' header will appear in title font (refer to design below). When user hovers over the title, the following prose will appear in smaller text:

_"Manuscripts about the Virgin Mary in Ethiopia, Eritrea, and Egypt have beautiful paintings, also called illuminations or miniatures. The PEMM website includes 2,500+ manuscript paintings, created from the 1400s into the 1950s."_ 

**Paintings Reveal**
When you click on 'Featured Paintings' tile, there is drop down to three tiles (refer to design below). Each tile will have an illustration [a] with text located on top of the illustration.

1. (oldest - 14th C)
2. (middle - 18th C)
3. (newest - 20th C)

Above the tiles will be a short paragraph titled "Featured Paintings". The paragraph will have the following text:

"_The first  is from one of the earliest manuscripts (1400), the second is a [something], and the third is from one of the most recent manuscripts (19xx),_"

**Painting Link**
Each tile should be a link to the painting's detail page:

- /paintings/???
- /paintings/???
- /paintings/???

**Reference design  for Title**
<img width="675" alt="Screen Shot 2022-07-12 at 3 59 30 PM" src="https://user-images.githubusercontent.com/104459635/178611127-7c3b1ac4-887f-453f-9145-ddafb6821033.png">

**Reference design  for Painting Reveal**
<img width="806" alt="Screen Shot 2022-07-12 at 6 47 42 PM" src="https://user-images.githubusercontent.com/104459635/178611254-be2863c8-b680-4d10-b5bc-e28845c6c52e.png">

**Comment by elambrinaki** [comment]
access from the landing page, three tiles with the paintings, each tile is hyperlinked to a page with this particular featured painting

**Comment by blainealem** [comment]
- access from the landing page, three tiles with the paintings, each tile is hyperlinked to a page with this particular featured painting
- on each page, a text on top explaining why it has been chosen, then the image

Featured Paintings (https://github.com/PrincetonPEMM/pemm-issues/issues/46)
[EMML 9002 Madonna and Child]

When you click on Featured Paintings, it will take you to three tiles/images, which will be [a, b, c]. Clicking on each will take you to static pages with the web addresses /featured/paintings/125 (using the Macomber ID No. for the associated story), and so on.

**Comment by WendyLBelcher** [comment]
Featured Painting 1
![BOr 639 Cannibal as European](https://github.com/PrincetonPEMM/pemm-issues/assets/56000106/becff053-14bf-4767-b418-c6171046ced2)

**Comment by WendyLBelcher** [comment]
Featured painting 2
![Berlin 42 TM 1300s f27v Mary Christ black](https://github.com/PrincetonPEMM/pemm-issues/assets/56000106/bddf13d8-3090-4baf-8440-abff115157e9)

**Comment by WendyLBelcher** [comment]
Featured Painting 3
![Spencer Virgin child DS-1966 006-006](https://github.com/PrincetonPEMM/pemm-issues/assets/56000106/ab043af3-452a-4771-9e48-5c3060e88f17)
