### ISSUE TITLE
Story Detail Page: Implement the Manuscript Information Box

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#47]
As a researcher, I want to see the full list of manuscripts that contain a given canonical story.

**Comment by elambrinaki** [comment]
On the Story Detail Page, below the translation, there is a list of manuscripts that contain this canonical story. The list is organized by century, and it contains manuscript names and folio starts (where this story ID appears in a manuscript).
The text reads: "The story appears in the following manuscripts:
1400s: BOr 413 f. 3; Gayant f. 6; 1500s: BOr 520 f. 234; EMML 232 f 123"
Each manuscript name is hyperlinked to the corresponding Manuscript Detail page.

**Comment by WendyLBelcher** [comment]
About 520 of our stories appear in 10 or less manuscripts. So, those stories should appear with all their manuscripts listed.

**Comment by WendyLBelcher** [comment]
The rest, about 458, appear with anywhere from 11 to 388 stories. Assuming that one manuscript takes about 15 characters, this is what 66 manuscripts would look like:

- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

That's not too bad.
Then this would be the length of 100 manuscripts: (edited) 

- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. (edited) 

I still don't find that bad. The Bishop story is about 2215 characters. So, if it had 100 manuscripts (it has way more, but for calculation), the list of manuscripts at the end would be half the length of the story. For our largest manuscript, 388, it would look like this: 

- Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

That is a lot, although, buried at the bottom of the page, I'm not sure I would mind it. Maybe we should ask Anisa to do a design so we can see. If we made the cut off 100 manuscripts, that would result in 115 stories that need separate pages

**Comment by elambrinaki** [comment]
@WendyLBelcher For IDs with long lists of manuscript names, I would imagine not a separate page with the full list, but a button "See all manuscripts that contain this story" that gives a user the full list on the same page. Anisa initially wanted to use such a button ("See more") for English translation on the Story Detail page. What do you think?

**Comment by WendyLBelcher** [comment]
Oh yes, excellent! That's the best plan.

**Comment by blainealem** [comment]
Hi @issacjohannli spoke to Wendy and noted that we still want to organize the manuscripts by century, as follows: 
1300s: 
1400s: 
1500s: 
1600s: 
1700s: 
1800s: 
1900s: 

We think that the maximum # of manuscripts that should show in total is 14 (or whatever you think is a good number that won't slow down the page). If there are no manuscripts for a specific century, you do not need to list the date. If all 14 manuscripts are from the 1900s, list all 14. But if there are >50 manuscripts, list 2 manuscripts per century and "see more"

**Comment by blainealem** [comment]
TOTAL STORIES | 976 |  
% OF STORIES W MORE THAN 300 RECORDS | 1.02% |  
% OF STORIES W MORE THAN 200 RECORDS | 4.10% |  
% OF STORIES W MORE THAN 100 RECORDS | 12.60% |  
% OF STORIES W MORE THAN 50 RECORDS | 24.90% |  
% OF STORIES W MORE THAN 25 RECORDS | 36.17% |  
% OF STORIES W MODE RECORD | 22.85% | Percent of stories that have 1 record
MEDIAN RECORD | 7 | 50% of stories have 7 records or less
MAX RECORDS | 404 | Highest # of records in one story
MIN RECORDS | 1 | Lowest # of records in one story

MODE RECORD | 1 | # of records that repeat most frequently
COUNTMODE | 223 | 223 stories have 1 record

**Comment by WendyLBelcher** [comment]
Re number of manuscripts per century:
1300s: [only one, so will only ever see one manuscript here]
1400s: [probably a total of 15 manuscripts]

**Comment by WendyLBelcher** [comment]
Talking with Jeremy, "can we sort them by the date of the manuscript?" First, he doesn't particularly need to see all the manuscritps right there. He is fine, and in the cases where the story appears in lots of manuscripts, he even prefers a separate See More page. The "See more" page manuscripts should be ordered very precisely by date, each appearing on a separate line. The results would have manuscript name, manuscript date range, and folio/scan.

**Comment by WendyLBelcher** [comment]
For final decisions on all of this, see https://docs.google.com/document/d/1gFwV628TvX1ANyWLlnMEugQswDZl7QQXCASHcbgTiwM/edit#heading=h.6b1ni3hly3xq
