### ISSUE TITLE
Story Detail Page: Cycle Hyperlink

### ISSUE THREAD

**Issue by elambrinaki** [PrincetonPEMM/pemm-issues#49]
As a researcher, I want to know all the stories related to this story and the type of their relation.

**Comment by elambrinaki** [comment]
On the Story Detail page, after the translation, there are hyperlinks to the related stories. For example, for IDs that are part of a cycle, there are links to other IDs from this cycle (column "Cycle Name" on the Canonical Story sheet). The text on the website is "See other stories from the cycle: X, Y, Z (with hyperlinks to these stories' Story Detail pages)". For IDs related to other IDs apart from being in the same cycle, use column "Stories Related to" and "Story Relation Type" on the Canonical Story sheet. The text on the website is "See related stories: X (a sequel)" (X comes from Stories Related to, "a sequel" comes from Story Relation Type)

**Comment by blainealem** [comment]
@ayo-gb @henokalem @WendyLBelcher this ticket is on pause since we need to complete the PEMM numbering for the stories before we can create the story cycle hyperlinks
