### ISSUE TITLE
Story Detail Page: Information Box

### ISSUE THREAD

**Issue by henokalem** [PrincetonPEMM/pemm-issues#52]
The box on the middle left hand of the page contains specific information about each story (story type, subjects, keywords, etc). The below sentences are what each information detail should look like and how to generate this information. All data fields are sourced from the PEMM Master File, Canonical Story sheet, unless otherwise noted. 

Header = Information (caps & bold - refer to image)

1) `Earliest Attested Instance of the Story` Maybe, not sure about this, but could use from `Story Instance Sheet `column `Manuscript Date Range Start` (column AM) and `Manuscript Date Range End` (column AN). And putting that with a hyphen in between, and putting wording in front "Earliest Attested Instance of the Story." So it would look like this: **Earliest Attested Instance of the Story: 1452-1479.** 

2) Use `Total Records` (column K) with these words in front "Total Instances in GMP:" So it would look like this: "Total Instances in GMP: 341"

2) **Story Type**: use column "Type of Story" (column AM). This should be prefaced by the wording: "Type of Mary Story:"

3) **Collection**: use column "Collection" (column AI). This should be prefaced by the wording: "Collection:"

4) **Cycle**: use column "Cycle Name" (if empty, skip this field) (column AJ).  This should be prefaced by the wording: "Cycle Name:"

5) **Keywords**: use column "Macomber Keywords'' (if empty, skip this field) (column H): These should be prefaced by the wording: "Macomber's Keywords for Story:"

6) **Subjects**: use column "Canonical Story Subject" (column AT). These should be prefaced by the wording: "Subjects of Story:"

6) **Canonical Incipits**: Loop through the story instance sheet and for every story that has Canonical Incipit column(column AB) as true then get the Incipit column(Column O) and Recension ID Column (column C) and add a row to the information section with the Incipit Column followed by Recension ID. If the Incipit column is empty don't display the entire row, if the recension column is empty don't display the recension part. These should be prefaced by the wording **Canonical Incipit 1** and then, if there is a second one **Canonical Incipit 2** and so on

7) **Number of incipits in PEMM Incipit Tool**: use column "Total Incipits in the ITool" (column W) and put the wording "Total Incipits in the ITool"

8) **Earliest manuscripts in which story appears**: use column "Names of Mss with Earliest Attestation" (column Y) [WLB: I think we can omit this given what will be at the bottom of the whole page but to discuss]

9) **ID numbers**: use columns "Hamburg ID"(column M), "Clavis ID"(column P), "CSM Number"(column N), "Poncelet Number"(column O), "Macomber ID"(column A). Must insert wording in front of each. The wording is Hamburg No., Hamburg Clavis No., Oxford CSM No., Poncelet No., Macomber No.

A **_draft_** reference image is attached, however in instances where the image does not entirely match the description provided above, please refer to the instructions noted above.

<img width="340" alt="detailPage" src="https://user-images.githubusercontent.com/17439057/164781803-c914ee65-6bdf-4d72-a365-38774d3ac393.png">

**Comment by blainealem** [comment]
1) If the data does not exist for any field, remove the line

**Comment by issacjohannli** [comment]
Hi @blainealem, @henokalem. Thank you for the feedback on this issue! 
Upon your request, I've done the following changes:

1. Added logic gates to hide data fields if they are null.
2. Corrected typos for the data variables.
3. Implemented all data fields according to the ticket specifications for the information widget.

<img width="436" alt="Screenshot 2022-06-21 at 1 02 50 PM" src="https://user-images.githubusercontent.com/67703799/174794612-197e0efd-cba9-46d5-8716-06b12cbfea15.png">

**Comment by WendyLBelcher** [comment]
Isaac we did a design change to the information box. It doesn't affect the programming per se, just the order in which data appears. Below is a visualization of this:
![Information box design](https://user-images.githubusercontent.com/56000106/176940152-5d245131-0c8d-4004-b67f-5c9d322ca259.png)

**Comment by WendyLBelcher** [comment]
@issacjohannli Also, we neglected to tell you that we need two other pieces of information for the Canonical incipit. At the end of each one (if there are more than one, which is rare) we need the manuscript and folio to appear. For example: ያሀዝባ (BOr 520, f. 120v-124r).

**Comment by issacjohannli** [comment]
> @issacjohannli we did a design change to the information box. It doesn't affect the programming per se, just the order in which data appears.

No problem at all @WendyLBelcher! Thanks for the design update. I will change the information widget accordingly.

**Comment by WendyLBelcher** [comment]
<img width="443" alt="information-widget" src="https://user-images.githubusercontent.com/56000106/177408245-e6049eeb-ef62-4256-804c-0974af1f4f4a.png">

**Comment by WendyLBelcher** [comment]
@issacjohannli Thank you for the above. The order is a little different:
`Content Information`
Type of Mary Story:
Collection:
Subjects:
Keywords:

`Technical Information`
Earliest Attested Instance of Story:
Earliest Manuscripts in which Story Appears: [We will cut these down to three or four manuscripts]
Total in PEMM Manuscripts:
Total Incipits in the ITool:
Incipit(s):
ID Numbers:

**Comment by WendyLBelcher** [comment]
`Translation source `is moving to the Translation section #30 ticket, of the Story Detail page. We need that info, but not in these boxes.

**Comment by WendyLBelcher** [comment]
Some changes given to Isaac in Slack on the technical Informaton box on July 7, 2022:

- Strictly, now that I think about it, in the `Incipit(s) `field, only the first folio should appear, not the second one. (Most of the time, we want both, but here, the incipit appears only on one page, unlike the story, so it should be just the one.)So, "f. 120v" not f. 120v-124r.)
- Also, the period at the end of the story title needs to be added. And, if you are there, we should do proper citation style and have "In" at the beginning of the book title. So, it would be     Toledo." In _Täˀammərä Maryam (Miracle of Mary) Stories_...

Also, can we put the Amharic title in italics also? 
And, let's have diacritics, so not Ge'ez Print Editions but Gəˁəz Print Editions.
And a period at the end of the Translation & Editions titles. (I know, we have some with and some without periods, in the data, so that's really on us)

**Comment by blainealem** [comment]
ticket closed w bugs - refer to bug ticket
