### ISSUE TITLE
Manuscript Index Page: Create a table to display a list of all the manuscripts

### ISSUE THREAD

**Issue by henokalem** [PrincetonPEMM/pemm-issues#58]
Objective
- Create a table for the Manuscript INDEX page, that displays a list of all the manuscripts.

Notes
- Use the Material UI table similar to the story index page
- The table should include the fields from the following image
![image](https://user-images.githubusercontent.com/17439057/164787035-7ea3ac3b-356b-495e-92fb-fa8b82fcf80f.png)

**Comment by blainealem** [comment]
Moved to Phase 2
