### ISSUE TITLE
7Span: Home Page: Footer

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#64]
The footer will have both prose and links to other webpages on the website (as of 5/25/2022). Please refer to the design image below for additional guidance.

The outline for the left side (prose) of the footer is:
- [ ] **Logo**

- [ ] **Project Summary** 
"The Princeton Ethiopian, Eritrean, and Egyptian Miracles of Mary digital humanities project (PEMM) is a comprehensive resource for the 1,000+ miracle stories about the Virgin Mary in Ethiopia, Eritrea, and Egypt, and preserved in Gəˁəz between 1300 and the present."

- [ ] **Physical Address**
Princeton Department of Comparative Literature
133 East Pyne, Princeton, NJ 08540
Princeton Department of African American Studies
Morrison Hall, Princeton, NJ 08540
Princeton Center for the African World
Morrison Hall, Princeton, NJ 08540

- [ ] **URL**
pemm@princeton.edu

- [ ] **Copyright**
(c) The Trustees of Princeton University

**Comment by WendyLBelcher** [comment]
The pages the links go to appear in the Structure ticket. #24

**Comment by WendyLBelcher** [comment]
For Wendy: Research Posts will include the information on our old pages of Research Questions, Research Answers, and PEMM Datasite. (Or, maybe under News, but here is better I think.)

**Comment by WendyLBelcher** [comment]
Update:
The links in the middle of the footer will be:
`About ` links will go to these pages: 
- [ ] `Our Mission` to /about/our-mission
- [ ] `Our History` to/about/our-mission

- [ ] `Our News `to/about/our-news
- [ ]  `Our Events` to/about/our-news
- [ ]  `Volunteer `to /about/our-news

- [ ] `Our People` to /about/our-people
- [ ] `Our Funders` to /about/our-people

- [ ] `Give Feedback` to /about/feedback

**Comment by WendyLBelcher** [comment]
Old outdated links in the middle of the footer will be:
`About ` links will go to these pages: 
- [ ] `Our Mission` to /about/our-mission
- [ ] `Our History` to/about/our-mission (link to Our History section of the page)

- [ ] `Our Team` to /about/people (link Our Team section of page)
- [ ] `Our Partners` to/about/people (link to Project Collaborators section of the page)
- [ ] `Our Funders` to /about/people (link to Our Funders section of the page)


- [x] `Our News `to/about/connect
- [x]  `Our Events` to/about/connect
- [x]  `Volunteer `to /about/connect
- [x] `Give Feedback` to /about/connect

`Explore` links will go to these pages: 
- [x] `Find Stories` will go to /stories (the story index page)
- [x] `Find Paintings `will go /paintings (not sure about this one)
- [x] `Find Manuscripts ` will go to /manuscripts (the manuscript index page)

The links in the right side of the footer will be:
`Research` links will go to these pages: [not `Research Tools` as in screenshot]
- [x] `Incipit Tool` will go to /research/incipit-tool
- [x] `Arabic Manuscripts` will go to /research/arabic-manuscripts
- [x] `Arabic Stories` will go to /research/arabic-stories **[not depicted in screenshot]**
- [x] `Maps` will go to /research/maps **[not depicted in screenshot]**
- [x]  `Interchangeable Spellings of Ethiopic Terms` will go to /research/spellings  **[not depicted in screenshot]**
- [x] `Research Posts` will go to /research/research-posts
- [x] `Macomber Handlist` will go to /research/macomber **[not depicted in screenshot]**
- [x] `List of Repositories` will go to /research/repositories
- [x] `Bibliography` will go to /research/bibliography
- [x] `Using the Site` will go to /research/using-site
- [x] `PEMM Github Repository` will link to our Github
- [x] `Terms of Use` will go to /about/terms-of-use
- [x] `Accessibility` will go to /about/accessibility


![PEMM Footer 5 31 2022](https://user-images.githubusercontent.com/56000106/173161095-932d3471-3104-4de6-b630-4cc484f54d5e.jpg)

**Comment by blainealem** [comment]
For Wendy: Research Posts will include the information on our old pages of Research Questions, Research Answers, and PEMM Datasite. (Or, maybe under News, but here is better I think.)

**Comment by blainealem** [comment]
NOTES FOR FOOTER: 1) Add the updated logo
2) Remove all caps to just first letter caps (matching the design)
3) Format the font to mimic design (pending Anisa)
4) Format the spacing between links to mimc design
