### ISSUE TITLE
Manuscript Repositories

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#71]

**Comment by WendyLBelcher** [comment]
List of Repositories is currently thought of as a static page. We would export what is in the Collections sheet, and it would like something like this:
**B-E (Yale), Beinecke Rare Book & Manuscript Library Ethiopic Collection, Yale University Library, United States, New Haven, CT**

Note: Scans not online. Shelfmark is Yale University Library Ethiopic 5.

**B-Dublin (CBL), Chester Beatty Library, United Kingdom, Dublin, Ireland.**
Note: BM = Lady Meux Ethiopic manuscripts described by Budge, One Hundred; Lady Meux 2 and 3 (publ. by Budge 1900, 1922 and 1923 [s. above]) are now ms. Oslo – London, Schøyen Collection, Ms. 248 (formerly Lady Meux 2 [= ms. A in CerMaria], ca. 1682–1706, 39 miracles) and ms. Dublin, Chester Beatty Library 914 (formerly Lady Meux 3 [= ms. B in CerMaria], cp. Cerulli 1965a: 290f., 40 miracles).B-E (Yale), Beinecke Rare Book & Manuscript Library Ethiopic Collection, Yale University Library, United States, New Haven, CT
[8:48](https://pemmworkspace.slack.com/archives/C03EG4MU29K/p1657036116492029)
Note: Scans not online. Shelfmark is Yale University Library Ethiopic 5.
[8:49](https://pemmworkspace.slack.com/archives/C03EG4MU29K/p1657036163347619)
B-Dublin (CBL), Chester Beatty Library, United Kingdom, Dublin, Ireland.
[8:49](https://pemmworkspace.slack.com/archives/C03EG4MU29K/p1657036165295129)
Note: BM = Lady Meux Ethiopic manuscripts described by Budge, One Hundred; Lady Meux 2 and 3 (publ. by Budge 1900, 1922 and 1923 [s. above]) are now ms. Oslo – London, Schøyen Collection, Ms. 248 (formerly Lady Meux 2 [= ms. A in CerMaria], ca. 1682–1706, 39 miracles) and ms. Dublin, Chester Beatty Library 914 (formerly Lady Meux 3 [= ms. B in CerMaria], cp. Cerulli 1965a: 290f., 40 miracles).

**Comment by WendyLBelcher** [comment]
So, the fields included from the Collections sheet, are 
Name | Collection Name | Institution Name | Country | City | Source

**Comment by WendyLBelcher** [comment]
Something nice to include, based on a formula in the spreadsheet, is the number of manuscripts we did from each. This is tough, it would need to loop through the Story Instance Sheet, for the Name of the Collection, but not including all the instances.

**Comment by blainealem** [comment]
@WendyLBelcher test

**Comment by blainealem** [comment]
@WendyLBelcher test

**Comment by WendyLBelcher** [comment]
I made slight changes to the wording of heads above, as shown in this pdf design (that is, changing "Name" to "Repository Abbreviation" and changing "Source" to "Source of Information on Collection." 
([PEMM List of repositories.pdf](https://github.com/PrincetonPEMM/pemm-issues/files/9302911/PEMM.List.of.repositories.pdf)
