### ISSUE TITLE
Bugs for Story Detail Information Box

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#74]
This ticket notes the bugs for the Story Detail Information Box original ticket #52 

### Screenshot of what’s there (8/19/22)
ID 106 The rich man who threw dry bread to a beggar in the name of Saint Mary.
<img width="286" alt="Screen Shot 2022-09-07 at 2 27 19 PM" src="https://user-images.githubusercontent.com/104459635/188867917-3bb3ac9e-2c18-4dd2-9c17-e7b837a1809f.png">

### Screenshot of what should be there (8/19/22)
Example of screenshot with all possible elements

<img width="270" alt="Screen Shot 2022-09-07 at 2 30 24 PM" src="https://user-images.githubusercontent.com/104459635/188868022-619c61ba-47eb-434d-8a3c-ef7cc34940db.png">

### Bugs (but with missing data that programmers cannot implement yet in brackets) (8.19/22)
Content Information
Type of Mary Story: 
Collection: [WLB: although, you likely don’t have this field/data yet so I’ve left it out]
Subjects:  [WLB: although, you likely don’t have this field/data yet so I’ve left it out]
Keywords:

Technical Information
Earliest Attested Instance of Story: [WLB: this is a date, e.g., 1737-1765]
Earliest Manuscripts in which Story Appears: [WLB: these are three or four manuscripts, no folios, from different repositories]
Total Manuscripts in which Story Appears:
Total Incipits in the ITool:
Incipit(s): [WLB: incipit should include its manuscript and folio; e.g., ያሀዝባ ያሀዝባ ያሀዝባ ያሀዝባ ያሀዝባ (BOr 520, f. 120v-124r)]
ID Numbers: [WLB: do not list IDs for which we have no numbers.Above has Cantigas and Poncelet with no IDs]

**Comment by henokalem** [comment]
@issacjohannli I was just looking at your most recent changes to get the story instances for a particular canonical story and I'm seeing somethings that don't make sense.
1. I had a already added code that gets all the story instances for a particular story [here](https://github.com/PrincetonPEMM/pemm-website/blob/b144a841fd9fd7c8d9a74daa2cb19eb98dbcfb64/src/pages/stories/%5BcanonicalId%5D.tsx#L101) so there should not be any reason to get that same data again [here](https://github.com/PrincetonPEMM/pemm-website/blob/b144a841fd9fd7c8d9a74daa2cb19eb98dbcfb64/src/pages/stories/%5BcanonicalId%5D.tsx#L81)
2. For your ticket that says get the manuscript date range start and date range end for a canonical story, I believe the goal of that ticket was for you to loop thorough all the story instances for a canonical story and find the earliest date and last date and place those two dates as the start and end of the canonical story, not just pick the [first story](https://github.com/PrincetonPEMM/pemm-website/blob/b144a841fd9fd7c8d9a74daa2cb19eb98dbcfb64/src/pages/stories/%5BcanonicalId%5D.tsx#L83) the api returns and use the date range start and end for that particular story instance.

**Comment by issacjohannli** [comment]
@henokalem 
The issue is fixed, will discuss it later in our weekly meeting.
