### ISSUE TITLE
Bugs for Story Detail Page Auto Generated Text 

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#75]
This ticket notes the bugs for the Story Detail Information Box original ticket #31

**Comment by WendyLBelcher** [comment]
Story Detail Page Auto-Generated Box
https://github.com/PrincetonPEMM/pemm-issues/issues/31
Screenshot of what’s there (8/19/22)
ID 106 The rich man who threw dry bread to a beggar in the name of Saint Mary.

Screenshot of what should be there (8/19/22)
Invented example

And 

Bugs: Layout & Highlighting & Wording
Each line should be separate from the line previous and indented.
I’m not sure about the final background and font color, but I think they are green and black. But wse what Anisa sent us, not the above (if they don’t match)
The main points should be highlighted somehow, as shown above with underscore. I believe Anisa thought that underscore would work best, as here. I kind of liked the idea of orange, but it didn’t look great.
Note the wording of each line above and change the web page to reflect it.
Add the * line, which includes two auto-generated elements, the date of the upload and the total number of PEMM manuscripts.
Bugs: Missing Data
The programmers don’t yet have the information for the standalone part.
The programmers probably do have the information for the read aloud part (column AC in Canonical Story sheet), but we can discuss.

**Comment by ayo-gb** [comment]
-Missing data/instructions for the post-life miracle sentence and the standalone sentence
- Changes to match new formatting, using the currently available instructions and info, are ready for deployment
