### ISSUE TITLE
Bugs for Story Detail Page Summary & Translation

### ISSUE THREAD

**Issue by blainealem** [PrincetonPEMM/pemm-issues#76]
### Ignore this comment
This ticket notes the bugs for the summary (#66) and translation (#30). 

Screenshot of what’s there (8/19/22)
ID 106 The rich man who threw dry bread to a beggar in the name of Saint Mary.
<img width="590" alt="Screen Shot 2022-09-14 at 7 07 43 PM" src="https://user-images.githubusercontent.com/104459635/190206244-8e104785-fa90-49db-83e2-251eb3912ea8.png">

Screenshot of what should be there (8/19/22)
Invented example

<img width="579" alt="Screen Shot 2022-09-14 at 7 07 54 PM" src="https://user-images.githubusercontent.com/104459635/190206261-540ef293-61dc-4c31-92c0-74f8d1e8b5c7.png">

Bugs: Missing info
Summary is not there
Translator and manuscript translated with folio not there
[WLB: done, fixed]

**Comment by blainealem** [comment]
@issacjohannli @henokalem we noticed some updates to the summary section, but its still not pulling the correct summary. Can you make sure the summary is being pulled from canonical story sheet, column BT ("Summary Plot")

**Comment by WendyLBelcher** [comment]
![story detail page bottom credit other](https://user-images.githubusercontent.com/56000106/200884649-fbff4af6-eac5-44c8-ab11-f6b2cb65607c.png)
Fields used
`Translation Sheet`
`canonical_story_id`
`canonical_translation_recension`
`language_translated_from` `language_translated_to` `translation_author` `translation_source_manuscript_name `translation_source_manuscript_folio `translation_as_of_date`
`translation_status  `
`published_translation_book_title` `published_translation_book_page_span`  `published_translation_book_item`

For the fourth column of the table (Location in MS):
Text to code: "f." ..., "col." ..., "line" ...
Fields to use: Story Instance sheet scan_start and scan_end or folio_start and folio_end and column_start line_start
Instruction:

If Story Instance sheet scan_start and scan_end have data, then pull that data and post it with an "s." in front and with an en dash between the numbers. Example: s. 24a-27b
If Story Instance sheet scan_start has data but scan_end is empty, then pull the information in scan_start with an "s." in front Example: s. 24a
If Story Instance sheet scan_start and scan_end are both empty, then pull the information in Story Instance sheet folio_start and folio_end and put them together with an en dash and an "f." in front Example: f. 24v-27r
If folio_end is empty, pull the folio_start only. Example: "5a, col. 1, line 12"
If column_start is empty, omit it
If column_start has data, pull it and put ", col." in front of it.
If line_start is empty, omit it
If line_start has data, pull it and put ", line" in front of it.
Data should appear in this order (scan/folio, column, line)

Example: "f. 5a-6b, col. 1, line 12"

**Comment by WendyLBelcher** [comment]
### E (OTHER TRANSLATIONS & EDITIONS OF THIS STORY)
Text to code: Add punctuation marks, as below
Fields to use: [lots, see below]
Example:
**French:** Gérard Colin. 2004. Le Livre Éthiopien Des Miracles De Marie (Taamra Mâryâm), item 10.

Instructions: Use the `Translation Sheet` and 
- for each `canonical_story_id`  (or should we use translation_id?)
- check if `canonical_translation_recension` is `false`. 
- If it is `false`, check if dropdown in `translation_status ` is _Published translation_ or _Complete Translation_ or _Complete Unpublished Translation_. 
- If it is, then display the content of `language_translated_to` and put it in bold and with a colon after it.
- Then, after that display the information in these fields: `translation_author`  `translation_as_of_date`  `published_translation_book_title`  with periods between each.
-
- Then, after, that, display the information in whichever of these two fields has data in it: `published_translation_book_page_span`  `published_translation_book_item` 
     - If `published_translation_book_page_span`  has data, display it with ", pages" in front of it.
     - If `published_translation_book_item` has data, display it with ", item" in front of it.
- Then, after that, display together the information in these fields: `translation_source_manuscript_name` 
-  `translation_source_manuscript_folio`. Display it with "From" in front of the first field and a comma between both fields.

- Example: **French:** Gérard Colin. 2004. Le Livre Éthiopien Des Miracles De Marie (Taamra Mâryâm), item 173, 174. From 
TGS (EOTC) 1996, p. 832-838. 
- Example: **Amharic:** Täsfa Gäbrä Śəllase. 2014. , p. 832-838

Future ticket, corrections of database needed before this can be done. We omitted the place of publication and we omitted full titles for all the Amharic translations. So, ignore the following instructions until this information has been corrected in the database.
In future, it will look like this:
**Amharic:** Täsfa Giyorgis. 1968. _Tä'ammərä Maryam Bä-Gəˁəz ənna Bä-Amarəñña [the Miracles of Mary in Gəˁəz and Amharic: 111 Miracles]_. Addis Ababa, Ethiopia, page 34.
**French:** Gérard Colin. 2004. Le Livre Éthiopien Des Miracles De Marie (Taamra Mâryâm). Paris: Les Editions du Cerf, item 10. From TGS (EOTC) 1996, p. 832-838.
