### ISSUE TITLE
7Span: 2.3 Stage: Website: Implement fonts and colors

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#83]
We are using the following colors: 

- Green 3C6F57
- Yellow E5A942
- Red DA232A
- Off-White E7E3DC
- Black 221F21

We are using the following fonts: 

- Header font (for logo mainly)
- Body font (Source Serif)
- Title font (Bold Source Serif)
- Menu font (Source non-Serif)
- Geez body font (Noto Serif and Noto Serif Bold).

[Pemm design guidelines colors fonts.pdf]
(https://github.com/PrincetonPEMM/pemm-issues/files/9302902/Pemm.design.guidelines.colors.fonts.pdf)

**Comment by blainealem** [comment]
Test

**Comment by WendyLBelcher** [comment]
Story Detail Page. There are a mix of fonts, probably from the section Ayo is working on and that Isaac is working on. We need it to be all in Source Serif, our website's font.
