### ISSUE TITLE
Updates for Story Detail Page Information Box 

### ISSUE THREAD

**Issue by WendyLBelcher** [PrincetonPEMM/pemm-issues#87]
@issacjohannli 

I gave you the wrong information for how to fix that date issue we discussed. Here is the correct information.

For the Story Detail page
In the TECHNICAL INFORMATION box.
to display  the right information in `Earliest Attested Instance of the Story:`

1. Loop through the `Story Instance` sheet for `date_range_mean` for a particular `canonical_story_id`. 
2. When you find the lowest number
3. Display the information in `manuscript_date_range_start` and `manuscript_date_range_end` as the `Earliest Attested Instance of the Story:` 
4. And, put them together with this specific dash: [–]

Example: For ID 4
**Earliest Attested Instance of the Story**: 1508-1551

**Comment by WendyLBelcher** [comment]
For the Story Detail page
In the TECHNICAL INFORMATION box.
to display the right information in `Incipit(s):`
Loop through the `story instance` sheet, for every story instance, where `canonical_incipit_boolean` is checked
Display the information in `incipit`
followed by
Display the information in `manuscript `and `folio_start` columns
Example, for PEMM ID 636:
Incipit(s); ወኮነ፡ እምድኅረ፡ ዕርገቱ፡ ለእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ ሎቱ፡ ስብሐት፡ በክልኤቱ፡ ዓመት፡ ወዘይበዝኅ፡ እምኔሁ፡ ወድኅረ፡ ብስራተ፡ ወንጌል፡ ቅዱስ፡ ተንሥኡ፡ ዓላውያን፡ ነገሥት፡ ወዓለዉ፡ ሃይማኖተ፡ ወነፈቅዋ፡ ለቤተ፡ ክርስቲያን፡ ወሰደዱ፡ መሃይምናነ፡ እለ፡ ኢአመኑ፡ በዕልወቶሙ FromVL-Vatican (BAV) 298, f. 120v

**Comment by blainealem** [comment]
- [ ] Please update to include canonical_story_subject from Keywords sheet under subjects. Refer to design image below for details
[01 Story Detail page revised WLBe.pdf](https://github.com/PrincetonPEMM/pemm-issues/files/10794527/01.Story.Detail.page.revised.WLBe.pdf)

**Comment by WendyLBelcher** [comment]
Note for return to sprint (not written properly, just a note): 
Loop through `Story Instance`
Find `date range mean` earliest
If find matching `date range means`, use `date range start` to select and display `date range start `and `date range end.`

**Comment by issacjohannli** [comment]
> 

@WendyLBelcher @blainealem The `Earliest Attested Instance of the Story` bug is fixed. Please see story ID 2 screenshot below.

<img width="1680" alt="Screenshot 2023-05-31 at 5 35 51 PM" src="https://github.com/PrincetonPEMM/pemm-issues/assets/67703799/73b88e6c-5fcd-4a8b-98db-5119c1e16037">
